### ISSUE TITLE
Undefined references building in Arch Linux

### ISSUE THREAD

**Issue by cmoralesmx** [dfranx/SHADERed#10]
Hello, I am having the following problem trying to make this application (I'm using Manjaro/Arch Linux)
After executing `cmake .` I got:  

-- Found SFML 2.5.1 in /usr/lib64/cmake/SFML  
-- Google Mock was not found - tests based on that will not build  
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cmoralesmx/git/SHADERed

Then, `make` works as expected until it reaches main.cpp.o 
An abreviated copy and paste of the log follows

[100%] Linking CXX executable bin/SHADERed  
/usr/bin/ld: CMakeFiles/SHADERed.dir/main.cpp.o: in function `setIcon(SDL_Window*)':  
main.cpp:(.text+0x185): undefined reference to `SDL_CreateRGBSurfaceWithFormatFrom'  
/usr/bin/ld: main.cpp:(.text+0x26c): undefined reference to `SDL_SetWindowIcon'  
/usr/bin/ld: main.cpp:(.text+0x278): undefined reference to `SDL_FreeSurface'  
/usr/bin/ld: CMakeFiles/SHADERed.dir/main.cpp.o: in function `main':  
main.cpp:(.text+0x738): undefined reference to `SDL_Init'  

A larger version of the log is available in [this pastebin](https://pastebin.com/BLmjyM8S)

Any help would be greatly appreciated. Thanks

**Comment by Houkime** [comment]
This can be fixed by having a find SDL2 section like this

```
# sdl2
pkg_check_modules(SDL2 REQUIRED sdl2)
```

but one should arrange IFs correctly so that it is triggered only on Linux.

**Comment by Houkime** [comment]
So the correct thing should be sth like this (keeping in line with the style of the rest of a document)

```
# sdl2

if(WIN32)

  find_package(SDL2 REQUIRED)

else()

  # link sdl2 on linux
  pkg_check_modules(SDL2 REQUIRED sdl2)

endif()

```

**Comment by dfranx** [comment]
Could you please test the fix @cmoralesmx ?

**Comment by cmoralesmx** [comment]
I can report the building is successful now. Thanks for the prompt solution!
