### ISSUE TITLE
Cannot open files in MacOS 10.15.4

### ISSUE THREAD

**Issue by samansepehri** [dfranx/SHADERed#101]
I am having problems opening files through the file browser window within SHADERed editor. Seems like files are disabled. 

<img width="1388" alt="Screen Shot 2020-06-09 at 21 51 14" src="https://user-images.githubusercontent.com/20922288/84225453-638c9880-aa9c-11ea-94dd-f0865ce8891c.png">

**Comment by dfranx** [comment]
Unfortunately, I can't help with this at the moment - I do not own a MacOS device so I can't test/fix this issue.
Thank you so much for reporting this bug though, I'll leave this open and fix it once I'll be able to do so.

**Comment by dfranx** [comment]
This should now be 100% fixed since I am now using file dialogs built with Dear ImGui rather then the previous native file dialogs.

Mind testing it though?

![FileDialogs](https://user-images.githubusercontent.com/30801537/88461941-496e1480-cea8-11ea-864f-55887d78d207.png)

**Comment by samansepehri** [comment]
Yes, I can confirm it's now working! Thanks @dfranx :)
