### ISSUE TITLE
No 2d Version HLSL

### ISSUE THREAD

**Issue by Tobias004** [dfranx/SHADERed#103]
I am a completely newbie to shader's and have the same problem as described in 
#94 but for HLSL. 
I plan to use the shaders with [win2d](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_PixelShaderEffect.htm)
I don't want to use vertex shaders at all. It would be a great help if there where a template for a minimal 2d HLSL shader to interactively learn 2d pixel shader development.

**Comment by AlvarezAriel** [comment]
Hi @Tobias004 

I'm a little late to the party but this is quite simple, here are the steps:

#### 1. On the default HLSL project, remove the Cube geometry and add a ScreenQuad geometry instead.
![Screenshot_2020-09-26_16-12-12](https://user-images.githubusercontent.com/2522433/94348497-1b758f80-0013-11eb-8db5-ad73ab22942e.png)

#### 2. Access the shader variable properties and select Orthographic projection for the matVP variable
![Screenshot_2020-09-26_16-11-32](https://user-images.githubusercontent.com/2522433/94348517-4e1f8800-0013-11eb-8bd5-aead28bb52c1.png)

From now on you can just ignore the vertex shader and use only the fragment shader.

**Comment by dfranx** [comment]
Ah, I apologize, I completely forgot to address this issue.
Thank you @AlvarezAriel for providing this tutorial.
Newer versions of SHADERed also come with a QuadHLSL/QuadGLSL template which does all of this steps for you.
