### ISSUE TITLE
[Question] How to pin variables

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [dfranx/SHADERed#107]
Hi,
thanks for your great work.

How do I pin variables. Could not figure it out ^^".

Cheers,
Georg

**Comment by dfranx** [comment]
Right click on the ShaderPass -> Variables -> click on the '+' icon.
It'll then appear in the "Pinned" window

![image](https://user-images.githubusercontent.com/30801537/87675505-bdf1d680-c777-11ea-8cf6-9f8b3c68e2e2.png)

**Comment by georg-eckert-zeiss** [comment]
Thank you.
