### ISSUE TITLE
[Question] Very simple setup example

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [dfranx/SHADERed#108]
Hi there,

unfortunately I could not get it to work. Can you point out, what I might be doing wrong? I guess this is a very typical starting point, so it might be interesting for other users too.

My Vertex Shader:

```hlsl
cbuffer cbPerFrame : register(b0)
{
	float4x4 World;
	float4x4 Projection;
	float4x4 View;
};

struct VSInput
{
	float3 Position : POSITION;
	float3 Normal : NORMAL;
};

struct VSOutput
{
	float4 Position : SV_POSITION;
	float4 Color : COLOR;
};

VSOutput main(VSInput vin)
{
	VSOutput vout = (VSOutput)0;

        float4 worldPosition = mul( float4( vin.Position, 1.0f ), World );
        float4 viewPosition = mul( worldPosition, View );
        vout.Position = mul( viewPosition, Projection );
	vout.Color = 1;

	return vout;
}
```

And the Pixel Shader:

```hlsl
struct PSInput
{
	float4 Position : SV_POSITION;
	float4 Color : COLOR;
};

float4 main(PSInput pin) : SV_TARGET
{
	return pin.Color;
}
```

I set World to `MatrixIdentity`, View to `MatrixLookAtLH` with Eye: (10,5,10), Focus: (0,0,0) and Up: (0,1,0), and Projection to `MatrixPerspectiveLH` with View size: (800,600), Near: 0,1 and Far: 100.

But I can see nothing. Any ideas?

Cheers,
Georg

**Comment by dfranx** [comment]
Hey there,
Just tested your example and it should work. Did you name your variables in the "Variable Manager" window exactly "World", "View" and "Projection"? SHADERed requires that names in that window must match the names in the shader code. 

Here's my project:
[HLSLsimple.zip](https://github.com/dfranx/SHADERed/files/4931758/HLSLsimple.zip)

You can also assign a "system value" to your matrix. These will update parameters automatically (for example: viewport size)
There are also plenty of examples in the `examples` directory.
You can also check this small tutorial I've written: https://github.com/dfranx/SHADERed/blob/master/TUTORIAL.md

**Comment by georg-eckert-zeiss** [comment]
Thank you. I'll try that.
