### ISSUE TITLE
Loading plugins doesn't work

### ISSUE THREAD

**Issue by schra** [dfranx/SHADERed#112]
**How to reproduce**

This is how I installed the plugin:

1. I followed the build instructions from https://github.com/dfranx/PluginShadertoy
2. I put the plugin into the correct folder:

   ```
   $ find /opt/shadered/plugins/
   /opt/shadered/plugins/
   /opt/shadered/plugins/ShadertoyImport
   /opt/shadered/plugins/ShadertoyImport/plugin.so
   /opt/shadered/plugins/README.txt
   ```

This is what I do:

1. Start Shadered
2. Project>Options>Plugins
3. The plugin "Shadertoy" is listed in the left column. Click on ">>"
4. Click ok to exit the dialog
5. File>Exit
6. Start Shadered
7. Project>Options>Plugins
8. Now the plugin "Shadertoy" is still in the left column. Furthermore the plugin is definitely not loaded because "File -> Import Shadertoy project" doesn't exist

**Information**

* Shadered version: 1.3.5 (I also tried to check the master branch, but [I can't compile it](https://github.com/dfranx/SHADERed/issues/111))
* OS: Arch Linux

**Comment by dfranx** [comment]
Works perfectly fine on my end. Can you please provide logs? Turn them on in Options -> General -> "Log" checkbox. Then click on ">>" button in the Options' "Plugins" section. Restart SHADERed and post logs here.

**Comment by schra** [comment]
Since #111 was fixed, I built the master version, and plugins work fine for the master version. If you are interested in the log files for 1.3.5 anyway, I'll provide them. But from my side it's enough that the master version fixes this problem.

**Comment by dfranx** [comment]
The log files are not necessary then. Glad it works.
