### ISSUE TITLE
Ubuntu 18.04 unable to start(v1.3.6)

### ISSUE THREAD

**Issue by DragonpeakStudio** [dfranx/SHADERed#114]
When I try to launch the version 1.3.6 binaries downloaded from the releases page I get the error(s)
```./SHADERed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./SHADERed)
./SHADERed: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./SHADERed)```

I am on Ubuntu 18.04.

**Comment by dfranx** [comment]
Sorry for late response. Do you have gcc installed and what version?
Might even be easier to compile it yourself.

**Comment by DragonpeakStudio** [comment]
I did try to build it before but got a series of errors along the lines of:
```
CMake Error at CMakeLists.txt:160 (add_subdirectory):
  The source directory

    /home/USER/bin/SHADERed/libs/spirv-headers

  does not contain a CMakeLists.txt file.

```
For a number of folders in /libs/

[CMakeOutput.log](https://github.com/dfranx/SHADERed/files/5012265/CMakeOutput.log)

My gcc version is ```gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0```

Thanks.

**Comment by dfranx** [comment]
Seems like you didn't run `git submodule update --init`?

**Comment by DragonpeakStudio** [comment]
After running that and updating cmake to 3.18.1 & gcc to 10.1.0 it appears to have worked. 
Thanks.
