### ISSUE TITLE
Severe visual glitches in v1.3.6

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [dfranx/SHADERed#115]
Hi there,
just downloaded v1.3.6 and launched it - unfortunately it is not usable. Let me know if you need more information:

![Shadered_136_Issue](https://user-images.githubusercontent.com/67101763/89046762-b886b580-d34d-11ea-9dd8-e100cd891224.png)

**Comment by dfranx** [comment]
Hello!
Unfortunately, there might be a problem with your GPU, not quite sure though. This issue doesn't appear on any of the machines I've tested it on.
What GPU do you have?

**Comment by georg-eckert-zeiss** [comment]
Hi @dfranx,
I recently had to re-install Windows 10. Just re-tried SHADERed 1.3.5 which worked flawlessly before - no luck there too. Seems to be a driver problem. I'll keep you up to date. GPU is Intel Xeon UHD Graphics P630 - dual with NVIDIA - which seems to have no driver installed yet.

**Comment by georg-eckert-zeiss** [comment]
Good news. Re-installing the driver for NVIDIA Quadro P2000 fixed the problem : )
