### ISSUE TITLE
Is there a profiling or execution timer or similar?

### ISSUE THREAD

**Issue by Fredrum** [dfranx/SHADERed#118]
Hi there!
This is great just what I was looking for! :) Very neat!
I'm exploring the fastest way I could do a gaussian blur and am wondering if there's a toggle or setting somewhere where I can see how fast a shader is?  So that I can compare different ones?

Cheers
Fred

**Comment by dfranx** [comment]
Hello. Thanks!
Unfortunately, there are almost no profiling tools/features in SHADERed. Though, I do have a few on my TODO list for v1.4.*/v1.5 releases. I'll add this to the list, so the feature will come in the near future. Thanks for suggestions!

**Comment by Fredrum** [comment]
Ok I'll keep an eye on your updates in the future and I will still use your program for my shader experiments!

**Comment by dfranx** [comment]
Hey! As promised, in SHADERed v1.5 (coming out in a week), there is a new "Profiler" window which contains information about execution time of a pass:
![PerformanceTimer](https://user-images.githubusercontent.com/30801537/110226423-657e6d80-7eef-11eb-9036-d4d7f5abaa02.gif)
![PerformanceTimerStatic](https://user-images.githubusercontent.com/30801537/110226424-67483100-7eef-11eb-9597-271d96810100.png)

**Comment by Fredrum** [comment]
That's amazing! :D  Nice once!
I will definitely pick up your new version!
I already used your program to test and build a fast two pass gaussian for my little project.
I worked on something else for a while and an am now back to that first idea again and this will come in handy I think as I am trying to optimize some CPU code on the Raspberry Pi by moving bit to the GPU.
