### ISSUE TITLE
Tutorial.md has some outdated info

### ISSUE THREAD

**Issue by Basssiiie** [dfranx/SHADERed#119]
Hey, there's some outdated information in the [Tutorial.md](https://github.com/dfranx/SHADERed/blob/master/TUTORIAL.md) file that might hinder new people to try it out.

- In the 1st paragraph of 'Shader pass', the option `File → Create shader file` does not exist anymore. There's `File → Create → HLSL` etc., but that seems create a completely new project template that overrides the empty project.

- Skipping the 'create shader file' by going straight to creating a shader pass causes the project to create GLSL files, which will cause strange errors when copy/pasting the code in the 'Shader code' section. Also the float4x4 types under the 'Variables' section don't show up anymore when the project is set to GLSL (where they're called mat4, but not everyone might know that). This could cause a lot of confusion when first trying out.

I hope it helps! Keep up the good work! I'm exited to try SHADERed out more tonight. 😄

**Comment by dfranx** [comment]
Hey! Thank you so much for reporting this. I'll soon rewrite the tutorial completely.

**Comment by dfranx** [comment]
I didn't manage to rewrite the tutorial completely... I did some changes though: [https://shadered.org/docs/tutorials.html](https://shadered.org/docs/tutorials.html)

& I made these two short video tutorials: [YouTube playlist](https://www.youtube.com/watch?v=vuJLpnL73As&list=PLK0EO-cKorzRAEfwHoJFiIldiyiyDR3-2)
