### ISSUE TITLE
Flatpak instructions incorrect on Ubuntu 18.04

### ISSUE THREAD

**Issue by stevewells20** [dfranx/SHADERed#120]
I don't have a lot of experience with flatpak, and have done no real configuration to it, so this may be a locally scoped problem. 

After running `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` ,

`flatpak install org.shadered.SHADERed`
Fails with:
"error: REMOTE and REF must be specified"

while 
`flatpak install flathub org.shadered.SHADERed`
installs SHADERed successfully.

**Comment by dfranx** [comment]
Thanks for reporting. I am not very experienced with the flatpak myself but this has been fixed in one of the pull requests.
