### ISSUE TITLE
Please support external text editor for shader

### ISSUE THREAD

**Issue by konlil** [dfranx/SHADERed#121]
SHADERed dosen't seems to update correctly, while I edited the vs/ps shaders within external text editor, such as Sublime Text or VS Code. Will this feature be supported in the future?

BTW, excellent work !

**Comment by dfranx** [comment]
Hello and thanks!
Can you please explain the "it doesn't update correctly" part more? I'll need more details. 

But SHADERed pretty much fully supports external editors - there are two checkboxes in Options -> General. You can make SHADERed open shaders in your default text editor & there's the "Compile shaders on file change" option that'll compile shader every time you hit CTRL+S in your external text editor (every time you make changes to the file). Works both on Linux and Windows.

**Comment by konlil** [comment]
"it doesn't update correctly" means it dosen't update at all.

But It's my mistake that I didn't notice the "Compile shaders on file change" option.

Thanks a lot. It works great now.
