### ISSUE TITLE
it crashes when save new project

### ISSUE THREAD

**Issue by jcyuan** [dfranx/SHADERed#126]
what i did: file -> new -> (anytype) -> paste my folder path into the filename field -> ok, then it just crashes... i thought it probably caused by the chinese characters of the folder path but it seems not because i tried english folder as well.

**Comment by dfranx** [comment]
You shouldn't paste the whole path in the filename textbox. You can press on the last slash at the top of the window and then paste the path.
But I'll fix it so that it doesn't crash.

**Comment by jcyuan** [comment]
yep thank you. because this is a habit from window using... directly paste path and enter will go into the folder.

**Comment by dfranx** [comment]
Added! I took a pause from the development so it's a bit late.
You can now enter full file path in the filename field and it'll work.
Also, a quick tip: you can press on the last slash `/` in the file dialog to enter a path too.

**Comment by aiekick** [comment]
in the last version of ImGuiFileDialog you can directly manually edit or imput a path by right click on the path buttons and enter for validation

![inputPathEdition](https://user-images.githubusercontent.com/1434736/104364464-e6843e80-5516-11eb-969d-361eaaf0c530.gif)

**Comment by dfranx** [comment]
I added this to my version of your ImGuiFileDialog library, but I forgot to make a PR, sorry! Right now though, I am working on my own file dialog library for Dear ImGui.

**Comment by aiekick** [comment]
ok np

**Comment by aiekick** [comment]
your new ImFileDialog is great haha. you took the same behavior as ImGuiFIleDialog but you went further.
I started working on a threaded texture loading for a thumbnail view. but your version is simpler than mine, 
and the quickacces is also a good feature (I hadn't thought about it) . 
I will be inspired by it :)
