### ISSUE TITLE
[feature request] reset view zoom to 100%

### ISSUE THREAD

**Issue by jcyuan** [dfranx/SHADERed#129]
a quick button to reset the view to 100%:

![image](https://user-images.githubusercontent.com/850854/92201108-3b031780-eeae-11ea-82cb-8d8c8f4b63bc.png)
like this, thanks so much!

**Comment by dfranx** [comment]
The only reason I haven't added such button is because I couldn't find an icon for it haha
But you can hold ALT key + double click on the preview window to reset the zoom.
And thanks!

**Comment by jcyuan** [comment]
wow~ got it, and thanks so much.
