### ISSUE TITLE
Using sampler2D as a function parameter and trying to debug at the same time causes a crash.

### ISSUE THREAD

**Issue by tofoz** [dfranx/SHADERed#132]
For some reason, if I pass sampler2D into a function and pixel inspect and fetch, it crashes.

Simply adding this function in without even calling it will cause the issue.
```
float test(sampler2D testMap) {
    return 0.5;
}
```

**Comment by dfranx** [comment]
Thanks for reporting this! I'll try to include a fix for this issue in the next release (should be out in 1-2 weeks).

**Comment by dfranx** [comment]
Thanks once again for reporting this. Should be completely fixed!
