### ISSUE TITLE
Not able to build proper input layout

### ISSUE THREAD

**Issue by torokze** [dfranx/SHADERed#142]
Hi,

Theres is no simple float in the drop-down box to properly define the input layout.

![image](https://user-images.githubusercontent.com/4497372/98467127-fe1c0f80-21d3-11eb-9266-281e0a9ad0d9.png)

**Comment by dfranx** [comment]
Hello,
thanks for reporting this issue. I somehow overlooked this after adding vertex buffer objects.
I can assure you that this will definitely be added in the next release of SHADERed!

**Comment by dfranx** [comment]
Thank you once again for suggesting this. It should now be possible in SHADERed v1.4.3 to create custom input layout. I'll add this stuff to docs too, but later.
