### ISSUE TITLE
Store configs and downloads on user owned folders

### ISSUE THREAD

**Issue by leiserfg** [dfranx/SHADERed#144]
SHADERed stores the config files and plugins next to the binary, that makes it hard to package it, maybe using https://github.com/sago007/PlatformFolders will be an easy way to solve the issue.

**Comment by dfranx** [comment]
But it shouldn't store config files and plugins next to the binary when you `make install` it.. at least not on Ubuntu.
It should store stuff into `~/.local/share/shadered`:
https://github.com/dfranx/SHADERed/blob/288f9c2b7df66a90a858016aafc0f88334a67e12/main.cpp#L93-L113 

Though it'd be great if someone helped with Linux stuff sometimes in the future. I've never used it too much myself so I don't know all the dos and don'ts. Plus the bigger the source code is the harder it is for me to manage everything by myself.

**Comment by leiserfg** [comment]
I guess the error happens because the heuristic suppose the installation will be done on `/usr/share/` but it does not need to be there (the pkg in AUR uses `/opt/` for instance). I guess a less error-prone way will be to check for writing permissions on the folder containing the binary, so if it's read-only it means you can't save there and then you need to use the user's folder.

**Comment by dfranx** [comment]
Thank you for the suggestion! I'll incorporate this solution in SHADERed v1.4.3

**Comment by dfranx** [comment]
Should be fixed now. Thanks once again for the tip!
