### ISSUE TITLE
Pause preview and toolbar

### ISSUE THREAD

**Issue by kparadis** [dfranx/SHADERed#145]
Hi,
I've been following tutorial and everything and one of the thing that blocked me for a very long time was that it was saying in the documentation to pause the preview to start debugging. Which was nowhere to be found.
May I suggest to either say in the documentation that you have to go into options and enable the toolbar to see that button (I've taught for a long time that it was the little eye icon) or enable the toolbar by default.
or maybe add it also elsewhere in the "file/project/window/help/supports" menu

And also, I think the status bar of the preview should be enabled by default. I've also searched a lot what I was doing wrong to not have this in my default project while trying to follow tutorials

Thanks

**Comment by dfranx** [comment]
Hey!
I messed up the commit message ( 383ed92acf9a3787523980a93f6ed734c2e5367b ), but I've both made the statusbar turned on by default and added to the docs how to turn it on/how to pause the preview.
Thank you so much for reporting this!
