### ISSUE TITLE
Building on Mac fails

### ISSUE THREAD

**Issue by GabZach** [dfranx/SHADERed#148]
I have downloaded version 1.4.2 as a ZIP, installed all the dependencies mentioned  in Readme.md,
and started the build process as described in Readme.md (cmake ../ from within build).

I get the error message:

```
CMake Error at CMakeLists.txt:156 (add_subdirectory):
  The source directory

    /Users/zach/Code/SHADERed/libs/assimp

  does not contain a CMakeLists.txt file.
```
and, indeed, that directory is empty.
A few others are empty, too, and make complains about it.

What is the proper way forward?
Are there more dependencies I need to install?
Why are the directories there, but empty?

Best regards, Gabriel

PS:
macOS version 10.15.7 (Catalina), with 3rd party libs from MacPorts.

**Comment by dfranx** [comment]
Hey!
When you download SHADERed as a .zip through GitHub, it won't also download the required submodules.
You should rather install git and then run these commands:
```bash
git clone https://github.com/dfranx/SHADERed.git
cd SHADERed
git submodule update --init
```

This should clone all the submodules too. Then you can just run `cmake` and `make`.
