### ISSUE TITLE
Building on MacOS: imgui_impl_opengl3

### ISSUE THREAD

**Issue by GabZach** [dfranx/SHADERed#149]
When building on macOS (10.15.7), I am running into this error from make:

```
CMake Error at CMakeLists.txt:188 (add_executable):
  Cannot find source file:

    libs/imgui/examples/imgui_impl_opengl3.cpp
```

However, that file does reside in `libs/imgui/backends/'.

What is the solution? Should I change the CMakeLists.txt ?

**Comment by dfranx** [comment]
The solution to this issue should be same as the solution to the #148 ( https://github.com/dfranx/SHADERed/issues/148#issuecomment-736542915 ), I think.

**Comment by GabZach** [comment]
Yes, seems to work with the libs pulled via git.

Suggestion: put these 3 command lines in the README.md

**Comment by dfranx** [comment]
Great! Glad it works!
They already are in the README.md:
![image](https://user-images.githubusercontent.com/30801537/100878490-8e373700-34aa-11eb-927b-77c3642d6845.png)

**Comment by GabZach** [comment]
Oh, well, I skipped the Linux section. Suggestions: set a textual "pointer" in the macOS section to the Linux section.
