### ISSUE TITLE
Make clearing RenderTexture optional

### ISSUE THREAD

**Issue by CptPotato** [dfranx/SHADERed#15]
As the title suggests, Render Textures are cleared every frame which usually is the desired behavior but doesn't allow for effects that accumulate or blend across multiple frames.

**Comment by dfranx** [comment]
Done! There is a checkbox now in the properties of the render texture. You can disable clearing with it.

**Comment by CptPotato** [comment]
Awesome, maybe I can put together something you can add to the examples.

**Comment by dfranx** [comment]
That would be awesome!! Hype! :D
PS: haven't released the binary for the v1.1.2 yet - I am working on the "Last frame" and "Inverse" flags you suggested.

**Comment by CptPotato** [comment]
Seems to work as expected 👍
closing the issue now
