### ISSUE TITLE
stdc++fs no longer needed with gcc>9.1

### ISSUE THREAD

**Issue by markusgod** [dfranx/SHADERed#157]
Hi, I am updating flatpak package and freedesktop runtime comes with gcc 10.3, it would be great if you make linking with stdc++fs conditional.

https://github.com/dfranx/SHADERed/blob/3535b674eb03d27e7f8a0eef8bea41ec14eccc84/CMakeLists.txt#L231

https://github.com/flathub/org.shadered.SHADERed/pull/10

https://stackoverflow.com/questions/62468531/linking-to-stdcfs-with-c20-still-necessary-when-using-filesystem

**Comment by dfranx** [comment]
Hello. Would this solution:
```cmake
if (CMAKE_COMPILER_IS_GNUCC AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9.2)
    target_link_libraries(SHADERed stdc++fs)
endif()
```
suffice?
Or should I add another variable (for example `LINK_FILESYSTEM`) and then do:
```cmake
if (LINK_FILESYSTEM)
    target_link_libraries(SHADERed stdc++fs)
endif()
```

**Comment by markusgod** [comment]
It would be great if you add variable. Thank you!

**Comment by dfranx** [comment]
Done (forgot to mention the issue in the commit message though).
Thanks for updating SHADERed flatpak once again! 😀
