### ISSUE TITLE
loading dds files as 3d textures

### ISSUE THREAD

**Issue by jandy123** [dfranx/SHADERed#159]
Not much of an issue, but rather a feature request.

I've attached a quick patch to support loading dds files and using them as 3d textures. Since I'm not familiar with the API, this is nothing more than a hack. However, It would be great though, if one of the devs could add proper loading and 3d texture support :).

Reading dds files is done using https://github.com/paroj/nv_dds. 

Thanks !

[3dtex.zip](https://github.com/dfranx/SHADERed/files/5719232/3dtex.zip)

**Comment by dfranx** [comment]
Hey! Thank you so much for this, never heard of `nv_dds` library. Could you maybe open a PR though? I'd love to add this but it's difficult to navigate the `diff` provided in your patch .zip so a PR would be awesome!

**Comment by jandy123** [comment]
@dfranx 
> Could you maybe open a PR though?

Well, just did that, though many mode mods had to be done wot compile in ubuntu 18.04 ;).

====

Again, this is just a very basic hack, adding support for just a subset of what that dds format can represent. 

Thanks for looking into this !

**Comment by dfranx** [comment]
Loading 3D (and 2D) textures from .dds files has been added to SHADERed v1.5. Thank you so much for suggestion!
