### ISSUE TITLE
GUIManager. CPP no find ImGui: : RenderPlatformWindowsDefault

### ISSUE THREAD

**Issue by alvinlyb** [dfranx/SHADERed#16]
Using Windows, vs2015 at compile time, prompt GUIManager. CPP file without ImGui: : RenderPlatformWindowsDefault... , has libs downloaded imgui

**Comment by dfranx** [comment]
So, have you called all of these commands:
```
git clone https://github.com/dfranx/SHADERed.git
git submodule init
git submodule update
```
?

It should work, unless somehow your git is cloning the Dear ImGUI's non-docking branch or if you are downloading the source code through GitHub's webpage?

**Comment by alvinlyb** [comment]
yes,Complete clone ： https://github.com/dfranx/imgui/tree/v1.71

**Comment by alvinlyb** [comment]
Can't find docking .Isn't it clone branch https://github.com/dfranx/imgui/tree/docking   ?

**Comment by dfranx** [comment]
Yes, that's the docking branch.

What version is your git?

**Comment by dfranx** [comment]
Read the README.md "Building" part. Closing
