### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by torokze** [dfranx/SHADERed#161]
Hello,

- The logging would be more verbose about shader compile errors.
- Where is the console window? (Write log messages to console window)
- Escape key handling to close dialogs

Zolee

**Comment by dfranx** [comment]
Hey. Thanks for the suggestions, though all three seem unlikely to show up in SHADERed.

**Suggestion 1**: If by "shader compile errors" you mean that SHADERed should be more verbose about syntax and similar errors, that's not up to me. The errors are reported by [glslang](https://github.com/KhronosGroup/glslang).

**Suggestion 2**: start SHADERed from the console by either going to the installation directory or having it in the PATH variable  and then typing "shadered". There's also already an option to write out log messages to console window (at the bottom of Options -> General page)

**Suggestion 3**: Again, I think that's up to Dear ImGui dev to implement. Not sure if there's any flag in Dear ImGui that makes this possible.

**Comment by huawei-ahcox** [comment]
Hi,

Suggestion 2 doesn't solve the problem on Windows 10. When started from the commandline on that platform, ShaderEd starts and then the cmd.exe terminal window becomes interactive again and no ShaderEd output appears there. This is with the option ticked.
Any suggestions for changing this?
