### ISSUE TITLE
In debug mode textures come in reverse order

### ISSUE THREAD

**Issue by mrazorvin** [dfranx/SHADERed#167]
For example: Following textures will comes in reverse order when I check content of variable in debug mode or during execution of Immediate expression (otherwise shader works correctly) 

```
uniform sampler2D IdleUp04;
uniform sampler2D IdleUp04N;
```

**Comment by mrazorvin** [comment]
UPD: after more tests, I  figure that to work correctly  I need to change texture order in Resource tab (to match debug order), then both modes start works correclty

**Comment by dfranx** [comment]
The "Unit" column in "Resources" window (or the number in the parenthesis when binding the texture) must match the location of the sampler2D in order for it to be bound correctly. By default, first sampler2D that appears in the code gets the bound to 0, second to 1, etc... You can also manually set the location of a sampler2D in the code with `layout(...)`.
