### ISSUE TITLE
NOT  BUILD !!!! !!! 

### ISSUE THREAD

**Issue by kaizer1** [dfranx/SHADERed#169]
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
The C compiler identification is MSVC 19.28.29335.0
The CXX compiler identification is MSVC 19.28.29335.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at CMakeLists.txt:133 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.
 

 
  This my file 
  # cmake toolchain
set(CMAKE_TOOLCHAIN_FILE "Q://DownloadsMain//vcpkg-master//vcpkg-master//packages//sdl2_x86-windows//share//sdl2//SDL2Config.cmake"
#"Q://DownloadsMain//vcpkg-master//vcpkg-master//packages//sfml_x86-windows//share//sfml"
#"Q://DownloadsMain//vcpkg-master//vcpkg-master//packages//glew_x86-windows//share//glew" 
#"Q://DownloadsMain//vcpkg-master//vcpkg-master//packages//glm_x86-windows//share//glm"
) 
if(CMAKE_TOOLCHAIN_FILE)
    include(${CMAKE_TOOLCHAIN_FILE})
endif(CMAKE_TOOLCHAIN_FILE)

# pkg
if (UNIX)
  find_package(PkgConfig REQUIRED)
endif()

 
Terrible readme files

**Comment by kaizer1** [comment]
And one more note - do not use vcpkg (absolute crap) as it downloads 32 bit versions of packages (at least SDL2 ) and nothing works.

**Comment by dfranx** [comment]
> Terrible readme files

Thanks for the constructive criticism.

> do not use vcpkg

As the readme says, no one forces you to use it. Use any package manager.

> as it downloads 32 bit versions

Download "sdl2:x64-windows".
