### ISSUE TITLE
Different Render Texture formats

### ISSUE THREAD

**Issue by CptPotato** [dfranx/SHADERed#17]
There doesn't seem to be a way to change the format of a render texture right now. Other formats are sometimes better suited or even required for effects to work. For example, this is needed when working with HDR rendering or buffers that require high precision.

On the graphics API side there's a lot of formats available, while the support on different platforms or older GPUs is probably hit or miss. As possible additions I suggest the 16 and 32 bit float variants with 4 channels (for example `DXGI_FORMAT_R16G16B16A16_FLOAT`/`DXGI_FORMAT_R32G32B32A32_FLOAT` in DirectX). These should be widely supported and offer a high precision & range, allowing for a wide range of use cases.

There are other interesting formats, too, which come into play when optimizing shaders but I'm not sure if this is worth the additional effort.

Edit: I just remembered there were some limitations in older APIs where using multiple rendertargets with different formats had drastic limitations. I'm not sure if SHADERed is also affected by this, which would make this feature pretty difficult to implement.

**Comment by dfranx** [comment]
Thanks for the suggestion! Implemented!

I have added a large number of texture formats. SHADERed requires OpenGL 3.3 core (which is somewhat new) so I don't think that there should be any problems with format support on older GPUs.

I don't think SHADERed is affected by those limitations. I tried using random formats in the deferred rendering example, and it kept working perfectly fine.  

Also, I am going to close this now, but if you find any bug feel free to open new issue related to that bug.

**Comment by dfranx** [comment]
Hey! I just want to notify you that I've released the binaries that include this feature + fix for GeometryTransform's last frame value.

PS: I have also added some nifty features that allow you to test your shaders in a more effective way - one of those features being ability to zoom in/out of the render texture (more info in changelog). This way you can see close-up of your AA shader.

**Comment by CptPotato** [comment]
@dfranx thanks again for the great work. I can confirm that the new RT formats and transform-fix work as expected. Though this new version has introduced 2 problems.

Sampler States (in my case for Render Textures) seem to have changed from linear filtering to point filtering with this update - causing problems when it comes to scaling and mixed resolution rendertargets:
![grafik](https://user-images.githubusercontent.com/3957610/64197358-26003c80-ce86-11e9-8849-eaed446972ac.png)
(notice the really choppy bloom effect)

I suspect it's because of the addition of the zooming feature (which I like btw. 👍).
The other issue is that something seems to mess up rendering of 3D Models (the ones generated internally still work). I don't have anything concrete to hint at, though.

**Comment by dfranx** [comment]
Thanks for testing so quickly!

Yeah, the bug came alongside the zooming feature.. If you can compile yourself then change these two lines https://github.com/dfranx/SHADERed/blob/master/Objects/ObjectManager.cpp#L78-L79 to use GL_LINEAR instead of GL_NEAREST otherwise wait 'till I push a fix tomorrow. It shouldn't even affect the zooming feature, I don't know why I have changed that :/

As for the second bug, I have no idea whats causing that problem.. It is so weird. I will investigate more tomorrow and hopefully push a fix..

Sorry for introducing major app breaking bugs with every release...

**Comment by dfranx** [comment]
I've actually found what causes the second bug too. Might push a fix now but if not just pass "item" variable as an argument here
https://github.com/dfranx/SHADERed/blob/master/Objects/RenderEngine.cpp#L219

**Comment by CptPotato** [comment]
> Sorry for introducing major app breaking bugs with every release...
No worries, I assume this is a one man project so updating it so frequently is probably a lot of work. I just ran into these issues because I used this app so much in the past few days 🙃.

I did some debugging and it seems that vertex data isn't bound properly which I think fits the issues you highlighted:
![grafik](https://user-images.githubusercontent.com/3957610/64202629-e8a1ac00-ce91-11e9-9bd0-08614074b038.png)

**Comment by dfranx** [comment]
Thank you for using it and reporting all these bugs and features! Helps a lot!

I have just pushed a hotfix for Windows versions (the Linux one is still broken)... It should work now - both render textures and models. I wasn't setting the matrices for models properly. Thanks for reporting once again! Hope all works now!

**Comment by dfranx** [comment]
@CptPotato have you tried the updated v1.1.3? Is it working now?

**Comment by CptPotato** [comment]
Yes, much better! Both the filtering and 3d models work again.
![grafik](https://user-images.githubusercontent.com/3957610/64251240-51cc0280-cf18-11e9-821a-927992748354.png)

**Comment by dfranx** [comment]
Damn that looks super nice!
