### ISSUE TITLE
not found/open sfml-audio.lib (Windows 10)

### ISSUE THREAD

**Issue by kaizer1** [dfranx/SHADERed#170]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: char const * __cdecl spvgentwo::Instruction::getName(unsigned int)const " (?getName@Instruction@spvgentwo@@QEBAPEBDI@Z) referenced in function "bool __cdecl spvgentwo::iterateInstructionContainer<class <lambda_264b93675b37d7b9ed29beb15b47b5d7>,class spvgentwo::List<class spvgentwo::Instruction> const >(class <lambda_264b93675b37d7b9ed29beb15b47b5d7>,class spvgentwo::List<class spvgentwo::Instruction> const &)" (??$iterateInstructionContainer@V<lambda_264b93675b37d7b9ed29beb15b47b5d7>@@$$CBV?$List@VInstruction@spvgentwo@@@spvgentwo@@@spvgentwo@@YA_NV<lambda_264b93675b37d7b9ed29beb15b47b5d7>@@AEBV?$List@VInstruction@spvgentwo@@@0@@Z)	SpvGenTwoCommon	Q:\Graphics\Shader\SHADERed\BuildLos\libs\SpvGenTwo\ModuleToString.obj	1

**Comment by dfranx** [comment]
Thanks for reporting. SHADERed doesn't use SFML anymore. Closing.
