### ISSUE TITLE
Fix for Deferred example shader compilation failure

### ISSUE THREAD

**Issue by ahcox** [dfranx/SHADERed#172]
I found the processing pixel shader for the deferred example failed to compile on Ubuntu / NVIDIA and Windows 10 / Intel.
Changing the clip line to these two lines fixed it:
```
const float div_zero = pos.w == 0.0 ? 0.0 : 1.0;
clip(div_zero - 1);
```
BTW, where are the examples located?

**Comment by KillerGoldFisch** [comment]
> BTW, where are the examples located?

Do you mean this?

https://github.com/dfranx/SHADERed/blob/2701b7b827b870ed3a04ba52f09490a6c87dbecd/bin/examples/DeferredRendering/shaders/ProcessingPS.hlsl#L23

**Comment by ahcox** [comment]
Yes, that’s the line.

________________________________

**Comment by dfranx** [comment]
Fixed! Thanks for reporting.
