### ISSUE TITLE
Texture can be added twice to project but SHADERed crashes when loading that project later

### ISSUE THREAD

**Issue by huawei-ahcox** [dfranx/SHADERed#174]
Version 1.4.2, Internal version 19.
Platform: Windows 10.

Log from the crash on load:

```
[13:17:40] Creating a texture img/slime_wide_003_lowres.png ...
[13:17:40] Creating a render texture LumaRT ...
[13:17:40] Creating a texture img/slime_wide_003_lowres.png ...
[13:17:40] (ERROR) Cannot create a texture img/slime_wide_003_lowres.png because that texture is already added to the project
[13:17:40] Opening an ObjectManager item in the PropertyUI
```

For context, the second copy of the texture was added to be able to use different min and mag filters.

**Comment by dfranx** [comment]
How were you able to add the second texture? SHADERed prohibits adding the same texture more than once to the project since it internally uses texture's path as an ID. I guess by editing the .sprj file?

I think the solution to this would be adding sampler objects to SHADERed. Though, I am not yet sure what they should look like UI-wise.

**Comment by huawei-ahcox** [comment]
> How were you able to add the second texture? SHADERed prohibits adding the same texture more than once to the project since it internally uses texture's path as an ID. I guess by editing the .sprj file?

In the GUI via the Objects tab.

I am able to create a second copy of the texture like that but not a third. See log when adding the texture to a file which already contains it:
```
[16:27:02] Creating a texture img\slime_wide_003_lowres.png ...
[16:27:19] Creating a texture img\slime_wide_003_lowres.png ...
[16:27:19] (ERROR) Cannot create a texture img\slime_wide_003_lowres.png because that texture is already added to the project
```

**Comment by huawei-ahcox** [comment]
> I think the solution to this would be adding sampler objects to SHADERed. Though, I am not yet sure what they should look like UI-wise.

Sounds right. It would be good to have a shortcut though: specify sampler state at the texture level as now rather than forcing people who use one sampler per texture to add a sampler object to their projects for every texture.

**Comment by huawei-ahcox** [comment]
Tried to repro with an empty project in same directory, adding same png that could be added to the original project. I could only add it once. Conclusion: my original project is corrupt in some way that allows this as a side effect.
