### ISSUE TITLE
This project is FANTASTIC!

### ISSUE THREAD

**Issue by ckaran** [dfranx/SHADERed#175]
I just wanted to say thank you for creating this!  I've always wanted to learn how to write shaders, but got hung up on debugging and the general difficulty of it all.  I think that with SHADERed I'll finally have a tool that makes writing and debugging shaders easy enough that I can actually sit down and learn them.  Thank you again for creating this!

**Comment by dfranx** [comment]
Aww thank you so much for this message, it means a lot! Glad that SHADERed can help you with learning how to write shaders! If you ever have some questions, feedback, etc... feel free to tell me. I'd love to help and further improve SHADERed.
