### ISSUE TITLE
Mods to make it compile under macOS

### ISSUE THREAD

**Issue by GabZach** [dfranx/SHADERed#183]
I have downloaded the latest version and tried to make it compile under macOS 10.15 (Catalina).

In order to achieve that, I had to modify the source code as follows.

In `libs/ImFileDialog/ImFileDialog.h` , I had to insert `#include <vector>` .
Otherwise you get some pretty funny compile errors regarding templates.

In `libs/ImFileDialog/ImFileDialog.cpp` , I had to replace
```
ImGui::TextWrapped("Are you sure you want to delete %s?", data.Path.filename().u8string());
```
by 
```
ImGui::TextWrapped("Are you sure you want to delete %s?", data.Path.filename().c_str());
```

I am not sure these are the proper ways to address the issues.
I just thought maybe somebody else runs into the same issues and would like to see a quick fix.

**Comment by dfranx** [comment]
Thank you so much for the feedback. Sorry for the slowness, this issue has somehow slipped under my eye... I've added these fixes to SHADERed.
