### ISSUE TITLE
Lots of question marks under Mac

### ISSUE THREAD

**Issue by GabZach** [dfranx/SHADERed#185]
When I run ShaderEd under macOS, the GUI has lots of question marks. See attached screenshot.
It seems to me a bug that is probably easy / possible to fix, since not all buttons / elements in the GUI are replaced by question marks. So, in principle, it should be possible.

![shadered-question-marks](https://user-images.githubusercontent.com/11965698/110254571-07559700-7f90-11eb-9f0e-c0e8829ec5eb.png)

**Comment by dfranx** [comment]
Seems like the font hasn't been loaded properly, both the normal font and the icon font. Have you placed the `data` directory (provided in SHADERed's repository) correctly?

**Comment by GabZach** [comment]
I have executed `make`, then launched it via `../bin/SHADERed`.

**Comment by clns** [comment]
You can manually copy the things from `bin/data` into your `build/bin/data` folder. Then I had to go into Options and uncheck "DPI aware", make sure the "UI scale" is 1.0 and it looks good now.

**Comment by GabZach** [comment]
Resolved with the current version. (No copying of config files needed.)
