### ISSUE TITLE
Function variable not work!

### ISSUE THREAD

**Issue by AllenPocketGamer** [dfranx/SHADERed#191]
Hello!

  I try to set a variable(float) on RenderPass as function variable, and the function variable type is `ScalarCos(PI/4)`.But actually, I get 0 in shader rather than the value which I want.

I am curious where 0 comes from, and finally I found out that it is the value set in the `pencil` button.

![捕获](https://user-images.githubusercontent.com/17348971/112751551-4b711000-9001-11eb-8f06-f0cd437f89dc.JPG)

So now I can't get the function type value because it's covered by the value set in the `pencil`.

Is this a bug or am I not doing something right?

**Comment by dfranx** [comment]
Hello!
Just checked the code behind ScalarCos/Sin and it turns out that the argument to ScalarCos/Sin needs to be in degrees rather than radians. So you should enter 45 rather than 0.785398...

Sorry for the slow response.

**Comment by AllenPocketGamer** [comment]
thx!
