### ISSUE TITLE
Can't select a geometry shader

### ISSUE THREAD

**Issue by golightlyb** [dfranx/SHADERed#195]
Starting with the simple example, click properties, and go to GS path. Click "..." to launch the file browser

I can edit the folder path as text in the file browser, but unfortunately I can't open any folders or files, or even close the file browser. I just have to quit the application.

File browser works fine if I just do "File > Open"

Debian Linux Stable

Nothing obvious in terminal output or log output

**Comment by dfranx** [comment]
Thank you so much for reporting this issue. This should now be fixed.

**Comment by golightlyb** [comment]
That was quick! Thank you 😊
