### ISSUE TITLE
Add support for display scaling (HiDPI)

### ISSUE THREAD

**Issue by supernes** [dfranx/SHADERed#2]
The editor is currently unusable on high-resolution screens. Here's a cropped screenshot from a UHD monitor with 250% UI scaling applied at system level.

![Annotation 2019-07-03 144158](https://user-images.githubusercontent.com/1689797/60588978-fd35cb00-9da0-11e9-997b-964acefc09cc.png)

**Comment by dfranx** [comment]
Hello! Thanks for reporting this bug. I just pushed a commit (+ made a release) that contains a possible fix for this bug. Could you please check it out and tell me if it is working properly now?
As I am inexperienced and haven't ever programmed anything that is DPI aware, this implementation might not fix the issue.

**Comment by supernes** [comment]
Thanks for the quick update! I just installed 1.0.2 and can confirm it's working now, good job.

DPI scaling on Windows is still something that many developers don't pay attention to, even experienced ones, so no need to worry about that :) One more aspect in which you are now ahead of the competition.

**Comment by dfranx** [comment]
No problem! Also, thank you for testing the fix!
