### ISSUE TITLE
Update Spirv-tools to the latest version to allow generate XCode project

### ISSUE THREAD

**Issue by krupitskas** [dfranx/SHADERed#203]
This was already fixed:
https://github.com/KhronosGroup/SPIRV-Tools/issues/4109

**Comment by dfranx** [comment]
It should be fixed now. I updated spirv-tools and spirv-headers to latest version

**Comment by dfranx** [comment]
I can't seem to compile it on Windows when I update both of these for some reason...

**Comment by dfranx** [comment]
Removed both of these libraries.
