### ISSUE TITLE
MacOS version crashed on launch

### ISSUE THREAD

**Issue by krupitskas** [dfranx/SHADERed#204]
Code part:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/5683877/117894828-dc582e00-b2c5-11eb-8616-d2cb20de3a11.png">
Stack:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/5683877/117894846-e67a2c80-b2c5-11eb-937c-8c9e155f4099.png">
Log:
```
2021-05-12 02:00:13.508678+0300 SHADERed[23216:281856] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x114b0b5d0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
(lldb) 
```

**Comment by krupitskas** [comment]
Fixed it via 
```
void* ptr = malloc(_bytes);//aligned_alloc(_aligment, _bytes);
```
in
```
void* spvgentwo::HeapAllocator::allocate(const sgt_size_t _bytes, const unsigned int _aligment)
```
Will take a look why aligned_alloc fails

**Comment by JannikGM** [comment]
> Will take a look why aligned_alloc fails

From the `aligned_alloc` man page:

> In addition, `aligned_alloc()` returns a `NULL` pointer and sets errno to `EINVAL` if size is not an integral multiple of alignment, or **if alignment is not a power of 2 at least as large as `sizeof(void *)`**

However:

```
Process [...] stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1 2.1
    frame #0: 0x00000001015e87e7 SHADERed`spvgentwo::HeapAllocator::allocate(this=0x0000000113606430, _bytes=32680, _aligment=1) at HeapAllocator.cpp:12:17
   9
   10  	void* spvgentwo::HeapAllocator::allocate(const sgt_size_t _bytes, const unsigned int _aligment)
   11  	{
-> 12  		m_Allocated += _bytes;
   13
   14  	#if defined(_WIN32) || defined(__CYGWIN__)
   15  		void* ptr = _aligned_malloc(_bytes, _aligment);
Target 0: (SHADERed) stopped.
(lldb) print _bytes
(const spvgentwo::sgt_size_t) $0 = 32680
(lldb) print _aligment
(const unsigned int) $1 = 1
```

So the alignment is smaller than allowed.

This alignment actually comes from here: https://github.com/dfranx/SpvGenTwo/blob/e9666b21d039dd06acdce7d02f2f17d66ff40a9f/common/include/common/HeapAllocator.h#L15

The crash was probably introduced by https://github.com/rAzoR8/SpvGenTwo/commit/0b1584e2bfd26499d5fcb38eba45d25cee6f7ab0 by @rAzoR8

**Comment by rAzoR8** [comment]
I fixed this issue in master here https://github.com/rAzoR8/SpvGenTwo/commit/1311c8962bbb2fd1cdf7b0d13dec52187d0c9425 and in linker here https://github.com/rAzoR8/SpvGenTwo/commit/13534715ef16decf6d2e80f69361ec4aa9740197

Sorry for the inconvenience :) I don't support MacOS and can't test there.

**Comment by JannikGM** [comment]
Thanks for the quick fix 👍 

However, I didn't try the code yet, but just looking at the diff, I believe this would still break for `Vector<char>`.
In that case, `alignof(char)` would still be 1, which is smaller than `sizeof(void *)`, so the allocation would fail.
Even if the code isn't currently doing that, there's a risk that it will break again in the future.

I think there should be a `aligment = std::max(sizeof(void *), aligment) // Fulfill POSIX alignment requirement` in HeapAllocator.cpp.
Another good addition would be a check to ensure that `aligment` [sic] is POT, which is requirement for Windows and POSIX.

**Comment by rAzoR8** [comment]
Hi again, sorry for the late response, here's another try to fix this for macOS: https://github.com/rAzoR8/SpvGenTwo/commit/da7fdd1214709620ff03db87ed927aa1d8aa1bcb 

If that still does not work, please consider making a PR at https://github.com/rAzoR8/SpvGenTwo, thanks! :)
