### ISSUE TITLE
Can't create textures on MacOS

### ISSUE THREAD

**Issue by krupitskas** [dfranx/SHADERed#207]
When Im trying to create object - texture, nothing happens.

**Comment by krupitskas** [comment]
Okay at first approach it does look weird for me.
```
ObjectManager.cpp
```

```
bool ObjectManager::CreateTexture(const std::string& file)
...
std::string path = m_parser->GetProjectPath(file);
...
data = stbi_load(path.c_str(), &width, &height, &nrChannels, STBI_rgb_alpha);
....
```
<img width="832" alt="image" src="https://user-images.githubusercontent.com/5683877/118538344-b9f76200-b756-11eb-8156-3c928f752d0b.png">

Looks like for some reason it adds current path, which is incorrect and it returns nullptr

**Comment by dfranx** [comment]
Thank you so much for writing such a detailed bug report and finding the cause of the bug!
It should now hopefully be fixed.
