### ISSUE TITLE
Add more spacing for scrolling in the objects bar

### ISSUE THREAD

**Issue by krupitskas** [dfranx/SHADERed#211]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/5683877/118676831-6b080600-b804-11eb-9578-aa9962e3f50a.png">
You can't scroll further and no place to click and create a new object. We need to add some padding here.

**Comment by deepaahuja92** [comment]
Hii! I am Deepa Ahuja. I know HTML,CSS and JS.Please assign this issue to me.

**Comment by dfranx** [comment]
Thanks for reporting, there's now 32px tall invisible element so it's easier to right click.

![image](https://user-images.githubusercontent.com/30801537/124333094-856b2880-db93-11eb-8d35-8c94580b0f92.png)
