### ISSUE TITLE
texture in GLSL

### ISSUE THREAD

**Issue by jcyuan** [dfranx/SHADERed#213]
hi, i'm sorry not sure if it's suitable to post question here,
because i only found how to use local image with HLSL on the official site in the doc, but there is no demo of GLSL...
so is it possible to bind local image in GLSL like this:

    uniform sampler2D tex;

thanks.

**Comment by jcyuan** [comment]
ok, i tried a few times and it works, solution:

just remember the binding order, and write your uniforms with these orders.
for example, bind 3 textures:
wordpos, wordnormal, and depth, 

steps:
1, create textures, there are a few ways to do this:
   a, project -> create -> texture
   b, in Objects frame window, directly drag your images into this frame
   c, in Objects frame window, right click and select create texture
2, right click on these textures you created -> bind, and remember the binding slot number for this texture
3, in your GLSL shader, write your uniforms according to these slot numbers you remember

    uniform sampler2D wordpos;    // slot 0
    uniform sampler2D wordnormal;   // slot 1
    uniform sampler2D depth;    // slot 2

if you wanna change the slot sequence, do:
right click on your default pipeline 'Simple' -> Resources -> adjust the sequence by clicking on those arrow buttons

besides, GLSL version in Shadered default to 330 which is available in WebGL2, so use 'texture(....)' instead of 'texture2D'. 

FYI

**Comment by dfranx** [comment]
Nicely explained! Thank you so much!

**Comment by ammein** [comment]
## IT WORKS! THANKS!

BUT, as for me, I need to add ScreenQuad as children of GLSL Pipeline to display the content. Like this:
<img width="451" alt="Screenshot 2022-10-19 at 2 42 58 PM" src="https://user-images.githubusercontent.com/25102828/196616429-f7279666-fe57-4546-9d98-cadc30a86b2f.png">

In `vertex` shader, I have to configure my screen view & texture coordinates like this:
```glsl
#version 330
out vec2 v_textureCoordinate;

void main()
{
	float x = -1.0 + float((gl_VertexID & 1) << 2);
	float y = -1.0 + float((gl_VertexID & 2) << 1);
	v_textureCoordinate.x = (x+1.0)*0.5;
	v_textureCoordinate.y = (y+1.0)*0.5;
	gl_Position = vec4(x, y, 0, 1);
}
```
