### ISSUE TITLE
it crashed.... but i have no idea why...

### ISSUE THREAD

**Issue by jcyuan** [dfranx/SHADERed#214]
i'm trying to debug a SSGI shader and it runs without any problem.

but if i try to debug, Shadered just crashes.... (whole software directly disappears)

what i did:

1. pause the shader
2. select a pixel from the preview window
3. click fetch button in the inspect window
4. crashes.....

i tried a few times, all the same.
is there some logs? i checked in the installation folder, and found nothing..

i can pack my shader up and put to somewhere if you want.

**Comment by dfranx** [comment]
Hello! Thanks for reporting!
Could you send me a minimal example of the shader project that causes the crash?

I don't think logs would help in this situation, I believe SPIRV-VM crashes when executing the shader.
But here is how to turn on the logs anyway: "Window" option in menu bar -> Options -> General -> at the very bottom of the General page you'll have various options for logging.

**Comment by jcyuan** [comment]
hi! @dfranx  thanks so much, i'll put my shader to somewhere and give you a link to download.
yes, i guess so, as you said, i think i'll not understand what the log wants to tell...

**Comment by jcyuan** [comment]
https://share.weiyun.com/c4NEz24E 
pwd: 66mwjk

@dfranx

**Comment by danilw** [comment]
@jcyuan this all because SPIR-VM bugged https://github.com/dfranx/SHADERed/issues/233
it not just crashes it also produce wrong result when not crashes

**Comment by jcyuan** [comment]
ok thanks @danilw i'll close this as i guess it will be hard to solve.
