### ISSUE TITLE
Crash trying to view texture properties

### ISSUE THREAD

**Issue by piranlbb** [dfranx/SHADERed#218]
Hi, I'm getting a hard crash with v1.5.3 when trying to view the properties on any texture object loaded from a file in either PNG or DDS format (oddly it does work if the file is a JPEG).

Steps:
1 - Create Texture in the object pane
2 - load a .png or .dds
3 - right-click the texture object and select Properties
4 - crash to desktop :(

Double-clicking the texture object does bring up the preview correctly though.
Also the log just says it's trying to open the properties panel, nothing useful in there I'm afraid.

**Comment by dfranx** [comment]
Hey!
Thanks for reporting the issue -- I think this should be fixed now.
