### ISSUE TITLE
3D Texture doesn't bind correctly when debugging

### ISSUE THREAD

**Issue by ryanw** [dfranx/SHADERed#219]
When using a 3D texture it's always blank while debugging, but works fine normally.

In a very trivial example I set every colour to that of the first pixel (pink), but while debugging it's always black. I tried to figure out the issue myself but don't understand where it behaves differently only when debugging.

[terrain-dds.zip](https://github.com/dfranx/SHADERed/files/6721134/terrain-dds.zip)

You can see on the left the preview of the texture, but when previewing the `uTex` during debugging it's totally blank.

![2021-06-28-155146_1882x915_scrot](https://user-images.githubusercontent.com/3372/123577967-eb208300-d828-11eb-8ab3-7d72be15a5ec.png)

**Comment by dfranx** [comment]
Thanks for reporting!
I forgot to handle the 3D texture object types in debugger's code.

It should be fixed now

![image](https://user-images.githubusercontent.com/30801537/124360125-55ba3000-dc28-11eb-8e6f-d63a1eb2257e.png)
