### ISSUE TITLE
libassimp

### ISSUE THREAD

**Issue by coderofsalvation** [dfranx/SHADERed#22]
Hi,

Linux ubuntu (xenial) user here.
This project looks very interesting!
So I ran:
```
$ sudo apt install libsdl2-dev libsfml-dev libglew-dev libglm-dev libassimp-dev libgtk-3-dev
```
However I got:

![Screenshot from 2019-09-21 10-11-20](https://user-images.githubusercontent.com/180068/65370390-78987180-dc58-11e9-8b9e-f5a1580cad69.png)

Some more info:

```
[sqz@localhost~]  $ cat /etc/issue 
Ubuntu 16.04.6 LTS \n \l

[sqz@localhost~]  $ find /usr/lib |grep assimp
/usr/lib/x86_64-linux-gnu/libassimp.so
/usr/lib/x86_64-linux-gnu/pkgconfig/assimp.pc
/usr/lib/x86_64-linux-gnu/libassimp.so.3
/usr/lib/x86_64-linux-gnu/cmake/assimp-3.2
/usr/lib/x86_64-linux-gnu/cmake/assimp-3.2/assimp-config.cmake
/usr/lib/x86_64-linux-gnu/cmake/assimp-3.2/assimp-config-version.cmake
/usr/lib/x86_64-linux-gnu/libassimp.so.3.2.0

[sqz@localhost~]  $ apt-cache search assimp
assimp-utils - 3D model import library (utilities)
libapache2-authcassimple-perl - Apache2 module to authenticate trough a CAS server
libassimp-dev - 3D model import library (development)
libassimp-doc - 3D model import library (documentation)
libassimp3v5 - 3D model import library
python-pyassimp - 3D model import library (Python bindings)
qt3d-assimpsceneparser-plugin - Qt 3D GL Transmission Format scene parser plugin
```

Next week I will pick up my new windows 10 laptop.
Will that be easier to run without OS plumbing?

**Comment by dfranx** [comment]
Hi,

I assume you downloaded the third-party libraries and then tried running the Linux binary I provided? I don't link assimp (and other libraries) statically currently. I recommend compiling SHADERed on Linux yourself. It isn't that difficult.

Windows version of the SHADERed should work from the get-go without a single problem though. Compiling on Windows should also be quite easy if you use some kind of package manager (like Microsoft's [vcpkg](https://github.com/microsoft/vcpkg)) to install all the needed libraries.
