### ISSUE TITLE
Debugger pulls the wrong slice from 3D texture

### ISSUE THREAD

**Issue by ryanw** [dfranx/SHADERed#229]
Thanks for fixing my previous issue with 3D textures. It mostly works now, however it looks like there may be a rounding error somewhere. The debugger hits the wrong slice sometimes. I've attached a .dds with numbers drawn on the first few slices.

[numbered.zip](https://github.com/dfranx/SHADERed/files/6759065/numbered.zip)

Video of it:

https://user-images.githubusercontent.com/3372/124367353-85aa1780-dcaa-11eb-8efe-b8f9d9466485.mp4

**Comment by dfranx** [comment]
Thanks for reporting the issue. This should possibly be fixed now!
