### ISSUE TITLE
Some GLSL `if` statements being ignored by debugger

### ISSUE THREAD

**Issue by ryanw** [dfranx/SHADERed#231]
This is a weird one so I've included an example project. Some simple `if` statements are not being evaluated when debugging. In the video I'm doing a check if `z < 0.0` which is ignored when it's part of a longer list of conditions, but does work when on its own. I'd expect this to cause a lot of problems for other people, but no one else has mentioned it? Maybe I'm doing something weird?

[weird-conditions.zip](https://github.com/dfranx/SHADERed/files/6780720/weird-conditions.zip)

https://user-images.githubusercontent.com/3372/124845078-0e49f000-dfea-11eb-80dc-d08721d82d3d.mp4

**Comment by dfranx** [comment]
Thank you so much for reporting this issue!

There was a bug in the VM where certain `OpLabel` instructions were skipped and `OpPhi` wouldn't work then.

It should work now:
![image](https://user-images.githubusercontent.com/30801537/125113472-fd33d880-e0e8-11eb-9383-af5de27ce3c4.png)

I appreciate the report so much!
