### ISSUE TITLE
Add image processing shader template

### ISSUE THREAD

**Issue by eszdman** [dfranx/SHADERed#237]
Or use the same vertex shader for all shader pass
It would be more convenient if the image processing shader was created in one click and was only pixel
Especially it gets more difficult with 10 step processing pipelines
![2021-07-31 03_43_18-](https://user-images.githubusercontent.com/45270494/127723400-3824c9a0-e7a9-4b13-a7f4-1d096b287e3a.png)

**Comment by dfranx** [comment]
Not sure if I understood correctly, but you can create custom templates: [https://shadered.org/docs/workspace.html#templates](https://shadered.org/docs/workspace.html#templates). This is great when you don't want to do repetitive process of creating 10 shader passes.
Just place a folder containing your project file into the `templates` directory (and rename the project file to `template.sprj`).

As for the vertex shader, you should be able to use the same one for all the shader passes (as far as I am aware).

**Comment by eszdman** [comment]
I have tried selecting an already created vertex shader text file when creating, but it becomes empty, it's bug or must be like this?
