### ISSUE TITLE
Is it possible to pan view while zoomed in!?

### ISSUE THREAD

**Issue by Fredrum** [dfranx/SHADERed#238]
Hello!!
I just installed your latest version on Linux having dabbled a bit about a year ago.
SHADERed is looking more fantasticer than ever!! :)  Such a nice and fun program!

I wanted to ask if there's a key+mouse combo to pan the render view while zoomed in?
I'd like to see what the pixels are doing up close and that would be helpful. I know you must have a huge to-do list so don't worry.
Just thought I'd ask! :)

Cheers and Thank You for this free software!

**Comment by dfranx** [comment]
Hey!
Thank you for the kind words, I'm glad you like SHADERed!
There actually is a combo that lets you pan around -- hold the left ALT key + right mouse button while moving the cursor.
Some other shortcuts:
 - you can ALT + double click with left mouse button to reset the zoom to 100%.
 - hold ALT + left mouse button while moving the cursor to select an area you want to zoom in

Hope this helps! Cheers!

**Comment by Fredrum** [comment]
Awesome thanks for the quick reply!
It seems like on my OS (Ubuntu) that combo is already used as instead of panning I get something like the Windowmanager's "Minimize", "Move" etc menu popping up.

I'll take a look and see if I can unset that in Ubuntu as that fuctionality is not something that I'd miss.
Thanks! I'll post back if that works out.
