### ISSUE TITLE
Can I set the Preview render resolution!?

### ISSUE THREAD

**Issue by Fredrum** [dfranx/SHADERed#239]
Hello!
Iv'e probably just missed the setting somewhere but can I set a fixed Preview render resolution somewhere?
I see that I can set the size of a render texture but I can't find that for the main Preview render.

Cheers!

**Comment by dfranx** [comment]
Hey! I am super sorry for a slow response.
Unfortunately, you can't change the resolution of the the main preview render texture.
But as you mentioned, you can set the size of a render texture so you could create a RT with your desired size and then just display that RT to the preview window.
