### ISSUE TITLE
Plane: front face culled ?

### ISSUE THREAD

**Issue by JPGygax68** [dfranx/SHADERed#244]
I'm trying to render a Plane, using a fragment shader that sets the fragment color (R, G) = texture coordinates (U, V).

Here's what it looks like from the back:
![grafik](https://user-images.githubusercontent.com/795272/131520406-e6f35acc-4321-49bb-afb4-b2f75080bc0e.png)
So far, so good: the color is black at (0, 0) and yellow at (1, 1).

But the same Plane refuses to render its front side:
![grafik](https://user-images.githubusercontent.com/795272/131520611-6b4bb7a8-c5ae-4105-8f4e-8164911db52d.png)

What am I missing ?

EDIT: I'm coming from OpenGL, so I'm interpreting the first screenshot as "front" and the second as "back".

**Comment by dfranx** [comment]
Hey! I apologize for the slow reply.

If you want both sides rendered, turn off culling (which is turned on by default).

To turn it off, add a "Render State" object above your Plane object (right click on shader pass -> `Add` -> `Render state`). Uncheck the "Cull" checkbox:

![image](https://user-images.githubusercontent.com/30801537/132111211-56951e9f-3b5a-4735-af80-8ba87db50fd3.png)

**Comment by JPGygax68** [comment]
Thank you, that will certainly be useful. That wasn't really the question though: what I don't understand is why the horizontal coordinates appear to be reversed. That would be expected if I were rendering the back side, but I'm not. 
Is something wrong with the Plane I'm using ? It's set to TriangleList, in fact all parameters are at their default values.

**Comment by n4074** [comment]
I believe the actual issue is that normal of the created plane is incorrectly reversed. `GeometryFactory::CreatePlane` appears to be using the opposite winding order to the other geometries.

**Comment by JPGygax68** [comment]
Thanks, that would explain it.

**Comment by bencresty** [comment]
I see the same issue (flipped coordinates) happening here. Why is this thread closed? It doesn't seems to be solved.
