### ISSUE TITLE
Build error on Flatpak with the FreeDesktop 21.08 runtime: `size_t` has not been declared

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#249]
**SHADERed version:** 1.5.4 (could be reproduced with 1.4.3 too)

While [trying to update the Flatpak to use the latest FreeDesktop SDK version](https://github.com/flathub/org.shadered.SHADERed/pull/15), I'm getting the following build error:

```
/run/build/shadered/libs/ShaderExpressionParser/Tokenizer.h:50:39: error: ‘size_t’ has not been declared
   50 |         Tokenizer(const char* buffer, size_t bufLength);
      |                                       ^~~~~~
```

This is not an issue with the older FreeDesktop 20.08 runtime because it uses an older GCC version. See this comment for the reason: https://github.com/flathub/org.shadered.SHADERed/pull/15#issuecomment-920460902

**Comment by dfranx** [comment]
Thanks for reporting, it should be fixed. I don't think `size_t` was needed there anyway.
