### ISSUE TITLE
Shadow Map with SHADERed?

### ISSUE THREAD

**Issue by ViperBling** [dfranx/SHADERed#252]
Recently I implement a blinn phong shading model with SHADERed, but had some problem with shadows. Is there any solution with shadow mapping by SHADERed? I'm a green hand at compute graphics. Anyone help? I'll appreciate it!
![re](https://user-images.githubusercontent.com/17715149/136256239-0c4bd7be-7701-4211-bdd7-a9ae7e84c4bb.png)
!

**Comment by dfranx** [comment]
Hey!
Yeah, you can create shadow mapping in SHADERed.. First position your camera where you want to cast shadows from (your light), then go to `Project &rarr; Camera snapshots &rarr; Add` and create a new 'camera snapshot' -- this will copy the view matrix of the preview camera.
You can now use this view matrix to render your scene to a depth map from a different/static perspective...

Here's a very simple (and old) example project
[ShadowMapping.zip](https://github.com/dfranx/SHADERed/files/7315686/ShadowMapping.zip)
