### ISSUE TITLE
Crash when debugging on Linux using v1.5.5

### ISSUE THREAD

**Issue by liusida** [dfranx/SHADERed#253]
I was using version 1.5.4, and everything is fine. Today I downloaded the v 1.5.5 from https://github.com/dfranx/SHADERed/releases/download/v1.5.5/Linux.zip and unzip it. 
Then I ran the executable, saw the colorful cube, pressed the `Pause` button, and in the `Pixel Inspect` I click the first `Run` button for debugging the frag shader.

![bug](https://user-images.githubusercontent.com/14249458/136724339-852099b6-b6b0-48dd-b02e-97f5060cf7a4.png)

And then, no matter I choose to `Step` or to `Stop`, the program crashed, with a `Segmentation fault (core dumped)` message.

I can still use v1.5.4 to avoid this, and thanks for the great tool.

BTW, my system is Ubuntu 20.04 LTS, with 5.4.0-88-generic kernel.
My nvidia driver is 470.63.01, and the card is GeForce GTX 1070 Mobile.

**Comment by MaKiPL** [comment]
Same for me on Win10Pro RTX 2060 notebook
