### ISSUE TITLE
how to share uniform in different pass

### ISSUE THREAD

**Issue by shuaibozhang** [dfranx/SHADERed#261]
like light pos

**Comment by dfranx** [comment]
Hey! Sorry for the slow reply.

Check out this example: [Simple Light](https://shadered.org/view?s=qtAFNPvHIE) (click the fork button to open it in SHADERed Lite).

Basically, after you add the variable in the different pass, click the edit button in the variable manager next to your variable. After a popup window opens, switch from the "Value editor" to "Function" type and select the "Pointer" function:
![image](https://user-images.githubusercontent.com/30801537/142793433-d8aa7864-e7fe-4915-b105-369caec4eca4.png)

Also, make sure that the both variables are of same type
