### ISSUE TITLE
Naming of matVP , matGeo, et al.

### ISSUE THREAD

**Issue by GabZach** [dfranx/SHADERed#262]
I recommend to use the original OpenGL names for the predefined matrices,
such as matModelToWorld , instead of matGeo.
This will create less confusion, and is a trivial thing to implement.

**Comment by dfranx** [comment]
You can name your variables however you want to. It doesn't have to be "matGeo" or any of the names I used.

Though, thanks for the suggestion, I might change the names of those variables in my examples at some point.
