### ISSUE TITLE
make error (glm)

### ISSUE THREAD

**Issue by meigel** [dfranx/SHADERed#27]
Ubuntu 18.04 make fails

> /home/martin/apps/SHADERed/UI/CubemapPreview.cpp: In member function ‘void ed::CubemapPreview::Draw(GLuint)’:
/home/martin/apps/SHADERed/UI/CubemapPreview.cpp:141:26: error: ‘ortho’ is not a member of ‘glm’
   glm::mat4 matVP = glm::ortho(0.0f, m_w, m_h, 0.0f);
                          ^~~~~
/home/martin/apps/SHADERed/UI/CubemapPreview.cpp:142:25: error: ‘translate’ is not a member of ‘glm’
   glm::mat4 matW = glm::translate(glm::mat4(1.0f), glm::vec3(m_w/2, m_h/2, 0.0f));
                         ^~~~~~~~~

**Comment by jthwho** [comment]
Looks like a missing header.  Here's a patch that got it to compile for me.
```
diff --git a/UI/CubemapPreview.cpp b/UI/CubemapPreview.cpp
index dd7ce7a..ea43412 100644
--- a/UI/CubemapPreview.cpp
+++ b/UI/CubemapPreview.cpp
@@ -4,6 +4,7 @@
 #include "../Engine/GLUtils.h"
 #include <glm/glm.hpp>
 #include <glm/gtc/type_ptr.hpp>
+#include <glm/gtc/matrix_transform.hpp>
 
 const char* CUBEMAP_VS_CODE = R"(
 #version 330
```

**Comment by meigel** [comment]
that fixes it!

**Comment by dfranx** [comment]
Thanks for reporting @meigel and thanks for the fix @jthwho !
