### ISSUE TITLE
How to create multi-pass shader? 

### ISSUE THREAD

**Issue by hful** [dfranx/SHADERed#281]
How to create a multi-pass shader such as [https://www.shadertoy.com/view/MsGSRd](https://www.shadertoy.com/view/MsGSRd).  "Import shadertoy plugin" dosen't work on this kind of shader.

**Comment by hful** [comment]
I figured it out

**Comment by Calinou** [comment]
> I figured it out

@hful How did you manage to solve this? Please comment here to document this :slightly_smiling_face:

**Comment by upgradeQ** [comment]
Try to port [this](https://www.shadertoy.com/view/mtSGDy
) shader. You need two passes in the pipeline, in the first one set RT (render texture ? ) to window 
,then your pass name; in the second pass in properties set RT to window and your first pass name.

In the Objects tab you should have a render texture and uncheck clear, right click and bind this texture to both passes.

I've ported that shader and it behaves similarly to the original, but I'm having trouble with others that use 3 or more passes.
It would be helpful if there was documentation on this subject.

**Comment by harrism76** [comment]
For anyone from the future looking for the same question like me.
I was also wondering about shadertoy buffers, i read it just a render target, your rendering to a buffer and then using it as a texture for sampler in another shader. Each BufferA, B, etc... will need its own shader pass and a render texture,Buffer. These render textures bind to a channel 0, 1,2,etc... then you uniform sampler2d them in. I attached a working jupiter from this link  https://www.shadertoy.com/view/XXjSRc . 

![shaderMultiPass](https://github.com/user-attachments/assets/d6cf1d83-e48c-4368-9474-28d1c750c1a4)
[Test.zip](https://github.com/user-attachments/files/17647003/Test.zip)

I dont think order matters, i dont have my shader pass or buffer lined up like shader toy, or at least i dont think i do
Now i can enjoy the complex shaders from shader toy
