### ISSUE TITLE
Add a vector-based application icon

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#39]
While working on #37, I noticed the repository only contains a 64×64 icon. This isn't a huge issue, but it can be nice to have larger icons for display on software app stores and the like.

@dfranx Do you have a vector source file for the icon? We could add it to the repository (preferably as a SVG). This way, we can generate higher-resolution variants when needed :slightly_smiling_face:

**Comment by dfranx** [comment]
@Calinou unfortunately, I do not have the vector source file for the icon nor do I know how to make one..
The icon is simply a "screenshot" from the examples/features/outline example.

Also, here's a 650x616 icon if it helps:
![icon](https://user-images.githubusercontent.com/30801537/71011033-05828800-20ed-11ea-8f43-36a257d64a04.png)

**Comment by Calinou** [comment]
I made an attempt at redrawing the icon as an SVG. It looks slightly different from the original and doesn't look as good when scaled down, so I wouldn't recommend switching to it just yet.

[shadered_icon.zip](https://github.com/dfranx/SHADERed/files/4269418/shadered_icon.zip)

## Preview

![shadered_icon](https://user-images.githubusercontent.com/180032/75592858-b4472b00-5a83-11ea-8067-43c744d68a93.png)

**Comment by dfranx** [comment]
It looks absolutely stunning! Good job!

I am not able to test it at the moment, but what causes it to not look good when scaled down? Also, what are the potential fixes? I am even up for a logo redesign. It doesn't have to perfectly match the current one.

**Comment by Calinou** [comment]
> I am not able to test it at the moment, but what causes it to not look good when scaled down? Also, what are the potential fixes?

I need to test it further, maybe I'm just being overly hash with myself. :stuck_out_tongue:

**Comment by dfranx** [comment]
Okay :smile: 
Can I use it in some places?
I want to test it on my website and see how it looks. And probably on the splash screen, if I ever add it.

**Comment by Calinou** [comment]
@dfranx Sure :slightly_smiling_face: 

I made a new version with fixed size (it's now square):

## PNG

![shadered_icon](https://user-images.githubusercontent.com/180032/75631347-571db780-5bf2-11ea-99de-fa4291ea59ac.png)

## SVG

[shadered_icon.zip](https://github.com/dfranx/SHADERed/files/4272236/shadered_icon.zip)

The SVG may not render correctly in browsers, so I would recommend taking the PNG and resizing it for use on the website.

**Comment by Calinou** [comment]
@dfranx Sure :slightly_smiling_face: 

I made a new version with fixed size (it's now square):

## PNG

![shadered_icon](https://user-images.githubusercontent.com/180032/75632055-96e79d80-5bf8-11ea-8ae5-87224354fb06.png)

## SVG

[shadered_icon.zip](https://github.com/dfranx/SHADERed/files/4272277/shadered_icon.zip)

The SVG may not render correctly in browsers, so I would recommend taking the PNG and resizing it for use on the website.
