### ISSUE TITLE
When opening a file, the application should start in a paused state

### ISSUE THREAD

**Issue by ctrlcctrlv** [dfranx/SHADERed#44]
If not by default, then optionally.

I want this because some of my shaders take around &#188; to &#189; second to generate a frame, which is OK for my intended use case.

Even if I tell SHADERed to render the preview at 1FPS, this still causes my PC to struggle.

**Comment by dfranx** [comment]
@ctrlcctrlv added!

I've also made some changes on how the "paused" state works. Now the preview window will be updated when user recompiles a shader or resizes preview window even if the preview is paused. In my opinion this is how it should work. This way user can modify the shader when paused on a specific frame to see the result, avoid unnecessary rendering (only render on a change), etc...
