### ISSUE TITLE
program crashed after saving

### ISSUE THREAD

**Issue by DannyGersh** [dfranx/SHADERed#45]
32bit release on Win10.
I saved by pressing ctrl+s.
Is this the right place to report this ?

**Comment by dfranx** [comment]
@DannyGersh yes, this is certainly the right place to report the bug.
Does this happen every time you press CTRL+S ? Can you turn on logging (and "Stream logs to log.txt" option), try to do CTRL+S and then provide the log.txt content? I need more info to help.

**Comment by DannyGersh** [comment]
I was following the tutorial from the menu bar
and saved when It was mentioned that the program might crash hh
after retracing my steps the program did not crash again.
I enabled logging and It does'nt seem to effect performance,
consider enabling logging by default.
I'll inform of future crashes

**Comment by dfranx** [comment]
@DannyGersh okay! If any other bug occurs, please let me know!
