### ISSUE TITLE
Writing two projects in the same directory overwrites their shaders!!!

### ISSUE THREAD

**Issue by ctrlcctrlv** [dfranx/SHADERed#49]
Consider a directory with two projects...`A.sprj` and `B.sprj`.

SHADERed by default saves its GLSL files as `shaders/SimplePS.glsl` and `shaders/SimpleVS.glsl`.

Meaning you cannot have two projects in the same directory! You will silently overwrite your other project!

I lost my `zhe.sprj`!!! :-( Luckily I had it backed up partially on the Medium post I wrote about it, but this is very sad and could have turned out very badly for me.

**Comment by dfranx** [comment]
So sorry for this inconvenience.
It shouldn't happen anymore. SHADERed now prepends the project name to the shader filename when saving shaders.

**Comment by ctrlcctrlv** [comment]
No problem. There's really no excuse for my not having checked it into a Git branch, or any of the myriad other ways to prevent program bugs or human error from losing work. Glad I caught it before I lost a lot of work; or before this bug bit a n00b, as it stands, the files on my Github Gist profile are mostly up-to-date.
