### ISSUE TITLE
Variable Manager dialog assumes HLSL, even on Linux

### ISSUE THREAD

**Issue by ctrlcctrlv** [dfranx/SHADERed#51]
At first I thought this was just some kind of shorthand, but it turns out that these are HLSL variable types. I know that this program supports DirectX also (@dfranx doesn't share my disdain for proprietary APIs), but on Linux, and Windows under OpenGL, (if that's possible,) it should not use the HLSL types.
![2020-01-19-185534_1259x432_scrot](https://user-images.githubusercontent.com/838783/72679745-20318d80-3aed-11ea-9bde-9c6babb8cdcd.png)

**Comment by dfranx** [comment]
Sure. Small fix. It should now display correct types (if HLSL is used -> display HLSL type names, otherwise show GLSL types)
