### ISSUE TITLE
Shared shader files do not refresh changes

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [dfranx/SHADERed#53]
If I'm using the same shader for 3 different passes, and I edit the shader in one of the pass's text editor, it will not refresh changes on the other open passes. I have to manually close and re-open that pass's shader text editor to see that my changes are in fact shared because they point to the same file.

**Comment by dfranx** [comment]
Thanks for reporting this! I've just pushed a fix.
Now only one instance of the same file can be opened. When recompiling that file, all shader passes that use that file will be recompiled too.
