### ISSUE TITLE
multiple render texture tutorial

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [dfranx/SHADERed#54]
It would be helpful if there was a tutorial on how to set up a set of passes that use multiple texture targets. I have a project that spits out 2 textures: the scene and the brightness colors. I'm trying to do a simple bloom program. I can see the output textures fine from my first pass but I can't use just those textures in the next pass without geometry.

EDIT: it seems multiple texture targets is working but I cannot seem to use a ScreenQuad for rendering to the window. I can use any other 3D geometry to see my results but I need it to be a ScreenQuad for post-processing effects

**Comment by dfranx** [comment]
Thanks for the feedback!
SHADERed currently lacks some good tutorials. Though, I will add some tutorials and documentation when I find some time for that.

---

To use your two textures in a next pass, you just right click and bind them. The number in the brackets  tells you the slot to which the texture is bound. So for example if it says 1 and you are using HLSL, you need to bind your texture to register t1.
To render these to your screen or another texture, you actually have to have a fullscreen rectangle. SHADERed tries to mimic how DirectX/OpenGL programs work, so you actually have to manually add that fullscreen rectangle. In SHADERed there are two types of fullscreen rectangles you can use, ScreenQuad and ScreenQuadNDC. ScreenQuad requires additional transformations using the orthographic projection matrix and the **geometry matrix**. Geometry matrix is used to scale, move and rotate the ScreenQuad. With these (necessary) transformations you can, for example, put two ScreenQuads side to side, or have a minimap like thingy, etc... ScreenQuadNDC's coordinates are already NDC, so they don't require any additional transformation. You just add the ScreenQuadNDC to your shader pass and have a simple vertex shader that just passes on the position to the pixel shader without any transformation.

To see ScreenQuad in action, you can check `DeferredRendering`, `Edge`, `Sobel`, `features/rt` examples that ship with SHADERed.
To see ScreenQuadNDC in action you can check the `features/compute/glsl` (or hlsl) example.

PS:
> you actually have to manually add that fullscreen rectangle

Well, when using for example OpenGL, you don't have to have geometry, you can just issue a draw call with lets say 6 points and then calculate their position in the vertex shader, but this currently isn't supported in SHADERed.

**Comment by TheMaverickProgrammer** [comment]
Thanks for mentioning the example folder. I didnt see that!
