### ISSUE TITLE
Deleting an item from the last pass deletes the item in the previous

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [dfranx/SHADERed#55]
I have 3 passes. In those 3 passes I have a Render State and a Screen Quad. If I right-click on the last pass elements, I see double entries. The last entries do nothing when I click on them. If I delete the item using the first entry, both the last pass and the previous pass have their items deleted!

![Untitled](https://user-images.githubusercontent.com/91709/73623691-80ebba80-4603-11ea-8ad1-0f4dc066c56d.png)

**Comment by dfranx** [comment]
Thanks for the report! That's because you have two items with the same name, that shouldn't be possible. And you are able to have two items with same name because I forgot to check if the name is taken when creating a Geometry item.

Should be fixed now!
