### ISSUE TITLE
Yes, No, Cancel buttons in dialogs could be always in view

### ISSUE THREAD

**Issue by H-G-Hristov** [dfranx/SHADERed#58]
![image](https://user-images.githubusercontent.com/47526411/75330564-f6a51800-5889-11ea-828a-19ed975c7ddb.png)

![image](https://user-images.githubusercontent.com/47526411/75330605-091f5180-588a-11ea-9b05-7f874878da09.png)

I think it makes sense to have the buttons in the modal dialogs always visible (on a separate button bar) and just to scroll the contents. I think that's more natural, intuitive and just looks better. Also not all dialogs should be resizable.

**Comment by Calinou** [comment]
The default dialog size could be made larger and non-resizable to avoid this.

**Comment by dfranx** [comment]
For now I'll just make certain dialogs larger.. I still have to test/improve UI scaling (which might an effect on this too) & other dialogs too.

**Comment by dfranx** [comment]
I've improved this with the commit 378df88a513248bbd972c0e1c66ceda72f1f49e8 . Thanks for reporting the issue!
