### ISSUE TITLE
libShaderDebugger link error

### ISSUE THREAD

**Issue by emericg** [dfranx/SHADERed#59]
Hi!
I'm trying to build the latest git on arch linux. It used to work well last time I tried (mid january) but now it look like libShaderDebugger fails to link.

Here is the full error :
```
[100%] Linking CXX executable bin/SHADERed
/usr/bin/ld : libs/ShaderDebugger/libShaderDebugger.a(CommonLibrary.cpp.o) : in function « sd::Common::lib_common_fma(bv_program_s*, unsigned char, bv_variable_s*) » :
CommonLibrary.cpp:(.text+0x61bf) : undefined reference to « glm::vec<4, float, (glm::qualifier)0> glm::fma<glm::vec<4, float, (glm::qualifier)0> >(glm::vec<4, float, (glm::qualifier)0> const&, glm::vec<4, float, (glm::qualifier)0> const&, glm::vec<4, float, (glm::qualifier)0> const&) »
collect2: erreur: ld a retourné le statut de sortie 1
make[2]: *** [CMakeFiles/SHADERed.dir/build.make:1144 : bin/SHADERed] Erreur 1
```
CommonLibrary.cpp, line 1445, `glm::vec4 vecData = glm::fma(a, b, c); `doesn't seem to accept glm::vec4 as parameters, I don't know why, but by commenting the first instance of `glm::fma()` the program build and run fine. I am running glm 0.9.9.7.

**Comment by RandomErrorMessage** [comment]
It appears that GLM has changed FMA behavior in 0.9.9.7: https://github.com/g-truc/glm/commit/95b1cdbbfed628a49fd00c4ab18fd0e4f59b8e9f

It will now use std::fma if it detects C++11 support. Old GLM behavior is trivial, and can be replaced with simple math.

glm::vec4 vecData = a * b + c;
/* glm::vec4 vecData = glm::fma(a, b, c); */

Sorry I didn't format this post in the GitHub style, I'm a very lazy person.

**Comment by emericg** [comment]
Thanks guys this is fixed!
