### ISSUE TITLE
OpenGL port

### ISSUE THREAD

**Issue by dfranx** [dfranx/SHADERed#6]
I have just pushed a commit which includes a complete recode of the program (+ some new features ;) )

Though, there are some things that are currently broken:

- HLSL geometry shaders
    - Not sure if this is my bug or [theirs](https://github.com/KhronosGroup/glslang) bug, or if HLSL geometry shaders now have to be coded in a specific way. A problem that I have stumbled upon is that it is quite impossible to send a variable (through output) from vertex shader to geometry shader. I think this is the issue: [link](https://github.com/KhronosGroup/glslang/issues/603) but apparently it seems fixed (?).
- MatrixReflect and MatrixShadow system variables currently do nothing and need to be reimplemented
    - glm, unlike DirectXMath, doesnt have a simple function to generate such matrices - so for now they will stay removed
- CMake adds unnecessary parts of the glslang to the build pipeline
    - glslang-default-resource-limits, SPVRemapper, glslangValidator, spirv-remap executables are being built even though they are not used anywhere...

Please report all the bugs that you stumble upon! :D

**Comment by dfranx** [comment]
Fixed CMake issue with commit https://github.com/dfranx/SHADERed/commit/ad6014b9ee22b0f0b1b2a57d8c1d3bd4325e076c

**Comment by Houkime** [comment]
Was waiting for it for a long time.
Thx dude.
Will test it right away on my Arch box.

**Comment by dfranx** [comment]
No problem!
Also please reply back with your thoughts and/or if you find any issues or think something should change.

**Comment by Houkime** [comment]
It seems like SDL2 is not properly linked (or included in main.cpp)

```
/usr/bin/ld: CMakeFiles/SHADERed.dir/main.cpp.o: in function `setIcon(SDL_Window*)':
main.cpp:(.text+0x185): undefined reference to `SDL_CreateRGBSurfaceWithFormatFrom'
/usr/bin/ld: main.cpp:(.text+0x26c): undefined reference to `SDL_SetWindowIcon'
/usr/bin/ld: main.cpp:(.text+0x278): undefined reference to `SDL_FreeSurface'
/usr/bin/ld: CMakeFiles/SHADERed.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x738): undefined reference to `SDL_Init'
/usr/bin/ld: main.cpp:(.text+0xad6): undefined reference to `SDL_GetCurrentDisplayMode'
/usr/bin/ld: main.cpp:(.text+0xd08): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: main.cpp:(.text+0xd17): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: main.cpp:(.text+0xd26): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: main.cpp:(.text+0xd35): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: main.cpp:(.text+0xd9a): undefined reference to `SDL_CreateWindow'
/usr/bin/ld: main.cpp:(.text+0xdba): undefined reference to `SDL_SetWindowMinimumSize'
/usr/bin/ld: main.cpp:(.text+0xde1): undefined reference to `SDL_MaximizeWindow'
/usr/bin/ld: main.cpp:(.text+0xdfe): undefined reference to `SDL_SetWindowFullscreen'
/usr/bin/ld: main.cpp:(.text+0xe0d): undefined reference to `SDL_GL_CreateContext'
/usr/bin/ld: main.cpp:(.text+0xe2d): undefined reference to `SDL_GL_MakeCurrent'
/usr/bin/ld: main.cpp:(.text+0x136a): undefined reference to `SDL_PollEvent'
/usr/bin/ld: main.cpp:(.text+0x149c): undefined reference to `SDL_GetWindowFlags'
/usr/bin/ld: main.cpp:(.text+0x151b): undefined reference to `SDL_GetWindowPosition'
/usr/bin/ld: main.cpp:(.text+0x1555): undefined reference to `SDL_GetWindowSize'
/usr/bin/ld: main.cpp:(.text+0x1652): undefined reference to `SDL_GL_SwapWindow'
/usr/bin/ld: main.cpp:(.text+0x1962): undefined reference to `SDL_GL_DeleteContext'
/usr/bin/ld: main.cpp:(.text+0x1971): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: main.cpp:(.text+0x1976): undefined reference to `SDL_Quit'
/usr/bin/ld: CMakeFiles/SHADERed.dir/GUIManager.cpp.o: in function `ed::GUIManager::GUIManager(ed::InterfaceManager*, SDL_Window*, void**)':
GUIManager.cpp:(.text+0x5364): undefined reference to `SDL_GL_SetSwapInterval'
/usr/bin/ld: GUIManager.cpp:(.text+0x5aa0): undefined reference to `SDL_GetWindowDisplayIndex'
/usr/bin/ld: GUIManager.cpp:(.text+0x5ac4): undefined reference to `SDL_GetDisplayDPI'
/usr/bin/ld: CMakeFiles/SHADERed.dir/GUIManager.cpp.o: in function `ed::GUIManager::Update(float)':
GUIManager.cpp:(.text+0x72ed): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: GUIManager.cpp:(.text+0x7d6c): undefined reference to `SDL_GetWindowSize'
/usr/bin/ld: GUIManager.cpp:(.text+0x934a): undefined reference to `SDL_SetWindowTitle'
/usr/bin/ld: GUIManager.cpp:(.text+0x94e7): undefined reference to `SDL_SetWindowTitle'
/usr/bin/ld: CMakeFiles/SHADERed.dir/GUIManager.cpp.o: in function `ed::GUIManager::SaveAsProject(bool)':
GUIManager.cpp:(.text+0xafeb): undefined reference to `SDL_SetWindowTitle'
/usr/bin/ld: CMakeFiles/SHADERed.dir/GUIManager.cpp.o: in function `ed::GUIManager::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
GUIManager.cpp:(.text+0xb490): undefined reference to `SDL_SetWindowTitle'
/usr/bin/ld: CMakeFiles/SHADERed.dir/GUIManager.cpp.o: in function `ed::GUIManager::m_setupShortcuts()::{lambda()#24}::operator()() const':
GUIManager.cpp:(.text+0xc338): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: CMakeFiles/SHADERed.dir/Objects/KeyboardShortcuts.cpp.o: in function `ed::KeyboardShortcuts::Load()':
KeyboardShortcuts.cpp:(.text+0x3b4): undefined reference to `SDL_GetKeyFromName'
/usr/bin/ld: KeyboardShortcuts.cpp:(.text+0x423): undefined reference to `SDL_GetKeyFromName'
/usr/bin/ld: CMakeFiles/SHADERed.dir/Objects/KeyboardShortcuts.cpp.o: in function `ed::KeyboardShortcuts::Save()':
KeyboardShortcuts.cpp:(.text+0x816): undefined reference to `SDL_GetKeyName'
/usr/bin/ld: KeyboardShortcuts.cpp:(.text+0x85a): undefined reference to `SDL_GetKeyName'
/usr/bin/ld: CMakeFiles/SHADERed.dir/Objects/KeyboardShortcuts.cpp.o: in function `ed::KeyboardShortcuts::GetString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
KeyboardShortcuts.cpp:(.text+0x1062): undefined reference to `SDL_GetKeyName'
/usr/bin/ld: KeyboardShortcuts.cpp:(.text+0x1133): undefined reference to `SDL_GetKeyName'
/usr/bin/ld: CMakeFiles/SHADERed.dir/UI/OptionsUI.cpp.o: in function `ed::OptionsUI::m_getShortcutString[abi:cxx11]()':
OptionsUI.cpp:(.text+0x896): undefined reference to `SDL_GetKeyName'
/usr/bin/ld: CMakeFiles/SHADERed.dir/UI/OptionsUI.cpp.o:OptionsUI.cpp:(.text+0x936): more undefined references to `SDL_GetKeyName' follow
/usr/bin/ld: CMakeFiles/SHADERed.dir/UI/OptionsUI.cpp.o: in function `ed::OptionsUI::m_renderGeneral()':
OptionsUI.cpp:(.text+0xfef): undefined reference to `SDL_GL_SetSwapInterval'
/usr/bin/ld: OptionsUI.cpp:(.text+0x2059): undefined reference to `SDL_GetWindowDisplayIndex'
/usr/bin/ld: OptionsUI.cpp:(.text+0x207d): undefined reference to `SDL_GetDisplayDPI'
/usr/bin/ld: CMakeFiles/SHADERed.dir/UI/PreviewUI.cpp.o: in function `ed::PreviewUI::OnEvent(SDL_Event const&)':
PreviewUI.cpp:(.text+0xa3b): undefined reference to `SDL_CaptureMouse'
/usr/bin/ld: CMakeFiles/SHADERed.dir/UI/PreviewUI.cpp.o: in function `ed::PreviewUI::Update(float)':
PreviewUI.cpp:(.text+0x24b4): undefined reference to `SDL_CaptureMouse'
/usr/bin/ld: PreviewUI.cpp:(.text+0x24cd): undefined reference to `SDL_GetMouseState'
/usr/bin/ld: PreviewUI.cpp:(.text+0x27be): undefined reference to `SDL_GetMouseState'
/usr/bin/ld: PreviewUI.cpp:(.text+0x2946): undefined reference to `SDL_WarpMouseInWindow'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/ImGuiColorTextEdit/TextEditor.cpp.o: in function `TextEditor::HandleKeyboardInputs()':
TextEditor.cpp:(.text+0x3296): undefined reference to `SDL_GetScancodeFromKey'
/usr/bin/ld: TextEditor.cpp:(.text+0x32c4): undefined reference to `SDL_GetScancodeFromKey'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_GetClipboardText(void*)':
imgui_impl_sdl.cpp:(.text+0x23): undefined reference to `SDL_free'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x28): undefined reference to `SDL_GetClipboardText'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_SetClipboardText(void*, char const*)':
imgui_impl_sdl.cpp:(.text+0x54): undefined reference to `SDL_SetClipboardText'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_ProcessEvent(SDL_Event const*)':
imgui_impl_sdl.cpp:(.text+0x25e): undefined reference to `SDL_GetModState'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x275): undefined reference to `SDL_GetModState'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x28e): undefined reference to `SDL_GetModState'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x2a7): undefined reference to `SDL_GetModState'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x2ed): undefined reference to `SDL_GetWindowFromID'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_Init(SDL_Window*, void*)':
imgui_impl_sdl.cpp:(.text+0x4bf): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x4d0): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x4e1): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x4f2): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x503): undefined reference to `SDL_CreateSystemCursor'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o:imgui_impl_sdl.cpp:(.text+0x514): more undefined references to `SDL_CreateSystemCursor' follow
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_Shutdown()':
imgui_impl_sdl.cpp:(.text+0x62d): undefined reference to `SDL_free'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x665): undefined reference to `SDL_FreeCursor'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_UpdateMousePosAndButtons()':
imgui_impl_sdl.cpp:(.text+0x6f9): undefined reference to `SDL_WarpMouseGlobal'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x72c): undefined reference to `SDL_WarpMouseInWindow'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x76c): undefined reference to `SDL_GetMouseState'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x824): undefined reference to `SDL_GetGlobalMouseState'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x838): undefined reference to `SDL_GetKeyboardFocus'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x89b): undefined reference to `SDL_GetWindowFlags'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x8c3): undefined reference to `SDL_GetWindowPosition'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x91b): undefined reference to `SDL_CaptureMouse'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_UpdateMouseCursor()':
imgui_impl_sdl.cpp:(.text+0x977): undefined reference to `SDL_ShowCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x9bf): undefined reference to `SDL_SetCursor'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x9c9): undefined reference to `SDL_ShowCursor'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_UpdateGamepads()':
imgui_impl_sdl.cpp:(.text+0xa16): undefined reference to `SDL_GameControllerOpen'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xa51): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xa80): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xaaf): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xade): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xb0d): undefined reference to `SDL_GameControllerGetButton'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o:imgui_impl_sdl.cpp:(.text+0xb3c): more undefined references to `SDL_GameControllerGetButton' follow
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_UpdateGamepads()':
imgui_impl_sdl.cpp:(.text+0xc85): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xd05): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xd85): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xe05): undefined reference to `SDL_GameControllerGetAxis'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_NewFrame(SDL_Window*)':
imgui_impl_sdl.cpp:(.text+0xf01): undefined reference to `SDL_GetWindowSize'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xf18): undefined reference to `SDL_GL_GetDrawableSize'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xfc1): undefined reference to `SDL_GetPerformanceFrequency'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xfd9): undefined reference to `SDL_GetPerformanceCounter'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_CreateWindow(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x113e): undefined reference to `SDL_GL_GetCurrentContext'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1151): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x116b): undefined reference to `SDL_GL_MakeCurrent'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1196): undefined reference to `SDL_GetWindowFlags'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x122c): undefined reference to `SDL_CreateWindow'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1250): undefined reference to `SDL_GL_CreateContext'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1262): undefined reference to `SDL_GL_SetSwapInterval'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1285): undefined reference to `SDL_GL_MakeCurrent'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_DestroyWindow(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x12f8): undefined reference to `SDL_GL_DeleteContext'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x131f): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_ShowWindow(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x1388): undefined reference to `SDL_ShowWindow'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_GetWindowPos(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x13da): undefined reference to `SDL_GetWindowPosition'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_SetWindowPos(ImGuiViewport*, ImVec2)':
imgui_impl_sdl.cpp:(.text+0x1453): undefined reference to `SDL_SetWindowPosition'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_GetWindowSize(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x14a5): undefined reference to `SDL_GetWindowSize'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_SetWindowSize(ImGuiViewport*, ImVec2)':
imgui_impl_sdl.cpp:(.text+0x151e): undefined reference to `SDL_SetWindowSize'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_SetWindowTitle(ImGuiViewport*, char const*)':
imgui_impl_sdl.cpp:(.text+0x1553): undefined reference to `SDL_SetWindowTitle'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_SetWindowAlpha(ImGuiViewport*, float)':
imgui_impl_sdl.cpp:(.text+0x1589): undefined reference to `SDL_SetWindowOpacity'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_SetWindowFocus(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x15b3): undefined reference to `SDL_RaiseWindow'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_GetWindowFocus(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x15dd): undefined reference to `SDL_GetWindowFlags'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_GetWindowMinimized(ImGuiViewport*)':
imgui_impl_sdl.cpp:(.text+0x1610): undefined reference to `SDL_GetWindowFlags'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_RenderWindow(ImGuiViewport*, void*)':
imgui_impl_sdl.cpp:(.text+0x165d): undefined reference to `SDL_GL_MakeCurrent'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_SwapBuffers(ImGuiViewport*, void*)':
imgui_impl_sdl.cpp:(.text+0x16a3): undefined reference to `SDL_GL_MakeCurrent'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x16b2): undefined reference to `SDL_GL_SwapWindow'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_CreateVkSurface(ImGuiViewport*, unsigned long long, void const*, unsigned long long*)':
imgui_impl_sdl.cpp:(.text+0x16f3): undefined reference to `SDL_Vulkan_CreateSurface'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_UpdateMonitors()':
imgui_impl_sdl.cpp:(.text+0x173e): undefined reference to `SDL_GetNumVideoDisplays'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1771): undefined reference to `SDL_GetDisplayBounds'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x17e4): undefined reference to `SDL_GetDisplayUsableBounds'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1849): undefined reference to `SDL_GetDisplayDPI'
/usr/bin/ld: CMakeFiles/SHADERed.dir/libs/imgui/examples/imgui_impl_sdl.cpp.o: in function `ImGui_ImplSDL2_InitPlatformInterface(SDL_Window*, void*)':
imgui_impl_sdl.cpp:(.text+0x19c1): undefined reference to `SDL_SetHint'
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x1a0c): undefined reference to `SDL_GetWindowID'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/SHADERed.dir/build.make:905: bin/SHADERed] Error 1
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/SHADERed.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I actually have previously made a small program using SDL2 but it was written in C and to find SDL2 I used pkg_config module of Cmake to do this (and it worked).
Also i need to notice that Cmake has a specialised module to handle SDL (although it is probably only SDL1).

Here is what i did in my small test program(i am not really adept at writing cmake yet)

```
cmake_minimum_required(VERSION 3.5)
project(sdl_test LANGUAGES C)

set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

add_executable(sdl_test
  main.c
)

include(FindPkgConfig)

pkg_search_module(SDL2 REQUIRED sdl2)
target_link_libraries(sdl_test SDL2 m)
```

"m" is for math

**Comment by dfranx** [comment]
Thanks for the report! Merged your pull request! Works now, right?

**Comment by Houkime** [comment]
yep it does

![image](https://user-images.githubusercontent.com/32805122/63950364-5cdfe800-ca6b-11e9-95c1-3cdccc2091ab.png)

**Comment by Houkime** [comment]
Although it seems like a FPS limiter would be nice.
When SHADERed is open i can hear chips in my PC singing (not fans)

**Comment by dfranx** [comment]
@Houkime there are several FPS limiters in the options:
- 60FPS limit when not focused
- custom FPS limit when focused (can be applied specifically to Preview window only or to whole app)
- VSync
And there is another one that turns on automatically when SHADERed is minimized and limits the FPS to 30.

**Comment by Houkime** [comment]
Right, see that now))
Thanks.

It doesn't seem like custom FPS limiting with properties is very solid though.
I can limit things to 60 but still have bursts of around 1000-1500 and 200-400.
Considering that FPS monitor only runs at certain intervals this might as well indicate that bursts are more frequent and i am just seeing them when they come in sync with FPS monitor.
Vsync is more solid in this regard.

**Comment by dfranx** [comment]
Yeah, I am aware of that. Though, I don't think I can fix that. AFAIK the sleep functions aren't that precise and doing it with some kind of loop would defeat the purpose of that feature - to lower down the CPU usage.
Although, I have never noticed big jumps to 1000-1500FPS.

**Comment by meigel** [comment]
Amazing that it is now available for linux! I unfortunately have some issues under Ubuntu 19.04. The binary requires libsfml-2.5 while only 2.4 is available. Maybe you could also provide a binary with statically linked libs?

> ../SHADERed-bin/SHADERed: error while loading shared libraries: libsfml-audio.so.2.5: cannot open shared object file: No such file or directory

Moreover, `make` results in an error with glm.

> make
[  6%] Built target HLSL
[  8%] Built target OSDependent
[ 10%] Built target OGLCompiler
[ 36%] Built target glslang
[ 44%] Built target SPIRV
[ 44%] Building CXX object CMakeFiles/SHADERed.dir/Objects/FunctionVariableManager.cpp.o
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp: In static member function ‘static void ed::FunctionVariableManager::Update(ed::ShaderVariable*)’:
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:140:20: error: ‘identity’ is not a member of ‘glm’
      matrix = glm::identity<glm::mat4>();
                    ^~~~~~~~
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:140:20: note: suggested alternative: ‘int_t’
      matrix = glm::identity<glm::mat4>();
                    ^~~~~~~~
                    int_t
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:140:38: error: expected primary-expression before ‘>’ token
      matrix = glm::identity<glm::mat4>();
                                      ^
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:140:40: error: expected primary-expression before ‘)’ token
      matrix = glm::identity<glm::mat4>();
                                        ^
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:195:20: error: ‘identity’ is not a member of ‘glm’
      matrix = glm::identity<glm::mat4>();
                    ^~~~~~~~
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:195:20: note: suggested alternative: ‘int_t’
      matrix = glm::identity<glm::mat4>();
                    ^~~~~~~~
                    int_t
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:195:38: error: expected primary-expression before ‘>’ token
      matrix = glm::identity<glm::mat4>();
                                      ^
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:195:40: error: expected primary-expression before ‘)’ token
      matrix = glm::identity<glm::mat4>();
                                        ^
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:250:20: error: ‘identity’ is not a member of ‘glm’
      matrix = glm::identity<glm::mat4>();
                    ^~~~~~~~
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:250:20: note: suggested alternative: ‘int_t’
      matrix = glm::identity<glm::mat4>();
                    ^~~~~~~~
                    int_t
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:250:38: error: expected primary-expression before ‘>’ token
      matrix = glm::identity<glm::mat4>();
                                      ^
/home/eigel/apps/SHADERed/Objects/FunctionVariableManager.cpp:250:40: error: expected primary-expression before ‘)’ token
      matrix = glm::identity<glm::mat4>();
                                        ^
CMakeFiles/SHADERed.dir/build.make:278: recipe for target 'CMakeFiles/SHADERed.dir/Objects/FunctionVariableManager.cpp.o' failed
make[2]: *** [CMakeFiles/SHADERed.dir/Objects/FunctionVariableManager.cpp.o] Error 1
CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/SHADERed.dir/all' failed
make[1]: *** [CMakeFiles/SHADERed.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dfranx** [comment]
Thanks for the suggestion, I will try to compile next version with statically linked libraries (although I tried before and had some problems with SFML - I will look more into it next time).

But honestly it is much easier to compile on Linux. It just takes few commands. As for your problems with `make`, they probably should be fixed now. Try pulling latest commit and compiling again.

**Comment by meigel** [comment]
Thanks for the update! You are absolutely right that building on linux is rather simple. There unfortunately still is an issue.

> [ 90%] Building CXX object CMakeFiles/SHADERed.dir/libs/pugixml/src/pugixml.cpp.o
[ 91%] Building C object CMakeFiles/SHADERed.dir/libs/nativefiledialog/nfd_gtk.c.o
[ 92%] Linking CXX executable bin/SHADERed
/usr/bin/ld: CMakeFiles/SHADERed.dir/Objects/ObjectManager.cpp.o: undefined reference to symbol '_ZNK2sf4Time9asSecondsEv'
//usr/lib/x86_64-linux-gnu/libsfml-system.so.2.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/SHADERed.dir/build.make:1507: recipe for target 'bin/SHADERed' failed
make[2]: *** [bin/SHADERed] Error 1
CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/SHADERed.dir/all' failed
make[1]: *** [CMakeFiles/SHADERed.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dfranx** [comment]
Hmmm seems like I forgot to link sfml-system library
Could you try changing this line:
```
find_package(SFML COMPONENTS audio)
```
into:
```
find_package(SFML COMPONENTS system audio)
````

I'll push a commit if that actually fixes the problem.

**Comment by meigel** [comment]
Same linker error I am afraid.

**Comment by dfranx** [comment]
Would placing a [FindSFML.cmake](https://github.com/SFML/SFML-Game-Development-Book/blob/master/CMake/FindSFML.cmake) file in the SHADERed/cmake directory work? Also sorry, I am kind of new to cmake

**Comment by dfranx** [comment]
Wait, before you place the FindSFML.cmake file try adding sfml-system on this line:
```
# link libraries
target_link_libraries(SHADERed ${OPENGL_LIBRARIES} ${GLM_LIBRARY_DIRS} ${SDL2_MIXER_LIBRARY} ${ASSIMP_LIBRARIES} glslang SPIRV sfml-audio)
```

**Comment by meigel** [comment]
`cmake` now complains about the sfml config. libsfml-dev is installed with apt and does not seem to provide cmake config files.
> CMake Warning at CMakeLists.txt:125 (find_package):
  By not providing "FindSFML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SFML", but
  CMake did not find one.
>
>  Could not find a package configuration file provided by "SFML" with any of
  the following names:
>
>    SFMLConfig.cmake
    sfml-config.cmake
>
>  Add the installation prefix of "SFML" to CMAKE_PREFIX_PATH or set
  "SFML_DIR" to a directory containing one of the above files.  If "SFML"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by dfranx** [comment]
Oh right, I think the config file was introduced in the 2.5 version. I've just pushed a commit that includes FindSFML.cmake . Pull those changes and then try to compile...

**Comment by meigel** [comment]
This works! All fine now. Cheers!

**Comment by dfranx** [comment]
Glad that it works now! Hopefully SHADERed also works properly. If a bug occurs please feel free to report it!

**Comment by dfranx** [comment]
I've changed it up a bit (since now it doesn't compile on my machine...)

If someone doesn't have SFML 2.5 installed, they should define the USE_FINDSFML variable:
```
cmake -DUSE_FINDSFML=ON .
```
Otherwise, just run
```
cmake .
```

**Comment by Calinou** [comment]
Should this issue be closed now?

**Comment by dfranx** [comment]
Hmm... I don't know, I've opened this issue mostly because I wasn't getting the right output from glslang when transcompiling a HLSL shader. But I haven't fixed that yet. Though, I will try my best to fix it in one of the upcoming updates.
As for the MatrixReflect and MatrixShadow, I guess I will remove them now.

But yeah, not sure.. I might leave this open until I fix HLSL geometry shaders?

**Comment by dfranx** [comment]
I've just seen that https://github.com/KhronosGroup/glslang/issues/1660 has been fixed. I guess I can finally close this issue as HLSL geometry shaders work again in SHADERed!
![HLSLGeometryShaders](https://user-images.githubusercontent.com/30801537/82212221-77683300-9912-11ea-9958-c6d8c887c9d2.gif)
