### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [dfranx/SHADERed#61]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AudioShaderStream](https://github.com/dfranx/SHADERed/blob/4d80aad6a178324ad6e268a3342c444ddcbb2ceb/Objects/AudioShaderStream.cpp#L21 "Destructor for AudioShaderStream")
- [ProjectParser::Open](https://github.com/dfranx/SHADERed/blob/3754bf4f1780c502c5cdee0cbbbfface9241dd16/Objects/ProjectParser.cpp#L191 "ProjectParser::Open function")

**Comment by dfranx** [comment]
Thank you so much for the tip - didn't know about that!

I hopefully removed all unnecessary checks. While doing this I've also realized I have used glDeleteShader instead of glDeleteProgram on couple of shader programs. Thanks!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/dfranx/SHADERed/commit/8ed04c4da532d9bc78bf9e704b22df20b6be7211 "Deletion of a few redundant checks").
