### ISSUE TITLE
CMake error related to glsl-parser

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#62]
- **OS:** Fedora 31
- **CMake version:** 3.16.3
- **SHADERed version:** Git https://github.com/dfranx/SHADERed/commit/e0194640cfff040513b84d9f73ffbdac732fa12a

After initializing and updating submodules, when trying to generate files using CMake, I get the following error:

```text
-- Configuring done
CMake Error at libs/ShaderDebugger/CMakeLists.txt:70 (add_library):
  Cannot find source file:

    libs/glsl-parser/ast.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at libs/ShaderDebugger/CMakeLists.txt:70 (add_library):
  No SOURCES given to target: ShaderDebugger


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by Calinou** [comment]
Nevermind, this can be fixed by using:

```text
git submodule update --recursive
```

If this doesn't work, try the following commands. Note that it will remove any changes you've made in the submodule folders:

```text
git submodule deinit --all --force
git submodule init
git submodule update --recursive
```

**Comment by dfranx** [comment]
Yeah, `--recursive` flag is now required since ShaderDebugger uses submodules..
I've added `git submodule update --init --recursive` line to the "Building" section of README.
