### ISSUE TITLE
The SHADERed process remains active after closing the window

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#65]
- **OS:** Fedora 31
- **SHADERed version:** Git https://github.com/dfranx/SHADERed/commit/c9a70a18e05516fdde13852babd20849c514ba6b

When starting SHADERed in a terminal, using it a bit then closing its window, the process remains active as seen on `htop`:

![image](https://user-images.githubusercontent.com/180032/75617071-749f4280-5b5a-11ea-9591-10cbda0566be.png)

It can be closed by pressing <kbd>Ctrl + C</kbd>, but it should terminate automatically once the window is closed. This way, the user doesn't need to terminate it manually before being able to enter other commands.

**Comment by dfranx** [comment]
Thanks for reporting!
I've looked into it and it seems that this only happens because of the "recompile on file change" option. I think the read() would sometimes block and the thread would stay hanging.
Anyway, could you please test the potential fix I've just pushed? It doesn't happen to me anymore.

**Comment by Calinou** [comment]
@dfranx The fix works when running the SHADERed binary in the `bin` folder, but not when running SHADERed installed system-wide. I don't know why.

**Comment by dfranx** [comment]
Interesting... now it happens to me too even when running from the bin directory...
Thank you for providing `strace` calls, I'll focus on this bug tomorrow.

**Comment by dfranx** [comment]
I've just pushed a commit that includes a possible fix for this bug.
Could you please test it? It doesn't hang for me anymore.
