### ISSUE TITLE
Build errors on macOS - source directory libs/ShaderDebugger does not contain a CMakeLists.txt file...

### ISSUE THREAD

**Issue by xinaesthete** [dfranx/SHADERed#66]
Tried following the instructions from the readme on building in macOS, but recieve a couple of errors about missing CMakeLists.txt files.

I'm not familiar with CMake (maybe now's a good time to start learning) and haven't tried to dig much further.

Looks like a really promising project, though - excited to have found it!

```
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /Users/peter/Documents/code/SHADERed/libs/ShaderDebugger

  does not contain a CMakeLists.txt file.


-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework   
-- Found GLEW: /usr/local/lib/cmake/glew/glew-config.cmake  
-- Found GLM: /usr/local/include  
CMake Warning (dev) at /usr/local/lib/cmake/assimp-5.0/assimpTargets.cmake:54 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/local/lib/cmake/assimp-5.0/assimp-config.cmake:1 (include)
  CMakeLists.txt:146 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found SFML .. in /usr/local/include
CMake Error at CMakeLists.txt:154 (add_subdirectory):
  The source directory

    /Users/peter/Documents/code/SHADERed/libs/glslang

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/Users/peter/Documents/code/SHADERed/cmake-build-debug/CMakeFiles/CMakeOutput.log".
```

**Comment by fnky** [comment]
You need to fetch submodules from within `libs`. You can either remove the existing repo and clone it with submodules:

```
git clone --recurse-submodules https://github.com/dfranx/SHADERed.git
```

or you can update existing repository to install submodules:

```
git submodule update
```

**Comment by dfranx** [comment]
It seems that your directories inside of the `libs/` are empty. Do the steps mentioned by @fnky.

**Comment by xinaesthete** [comment]
Thanks, I missed the common part of the instructions when reading the macOS part.  Will give it another try when I'm back on that machine.

**Comment by xinaesthete** [comment]
For the record, I then had problems related to the wrong version of Python being installed.  Installed pyenv & did `pyenv global 3.7.6` but this didn't allow me to progress until I also deleted CMakeCache.txt.

I now have a link error: `ld: library not found for -lassimp.5`.  Still possible that I missed something earlier.

I have been dabbling a bit with the app on Windows and while there may be one or two bits of UI I may have designed differently (takes a few clicks to get to uniform tweaking, would like to see a panel with sliders, dual monitor support - I would not be averse to potentially contributing) I am quite impressed, and very glad for the existence of the project.

**Comment by dfranx** [comment]
Unfortunately, there's not much I can do to help with those errors... Maybe you can check the issue #41 . 
As for the UI, there is already a window that makes modifying variables easy - it's called "Pinned". Basically, you can pin certain variables and they'll show up in that window (if that's what you've meant):
![Pinned](https://user-images.githubusercontent.com/30801537/75989803-35734780-5ef4-11ea-8759-633048b785b6.gif)

As for the dual monitor support, feel free to contribute if you want to. I would like to add support for it, but I only use 1 monitor - can't test it.

**Comment by xinaesthete** [comment]
No problem, I guess I'll treat this as an exciting opportunity to learn a bit more about CMake etc ;)

Thanks for the pointer to the variable pinning - I only really played with the program for a few minutes I must admit.

**Comment by fnky** [comment]
@xinaesthete The link error is likely because you haven't linked the Homebrew library at `/usr/local/lib`. I fixed this in the CMake configuration in the merged PR #70 — just fetch the latest changes and you should be good to go.

**Comment by GabZach** [comment]
Yes, my sub-dirs are empty, too.
Why are those not included when I download the whole project as a zip?

**Comment by fnky** [comment]
@GabZach When you download a zip file from GitHub it generates the zip archive using [`git-archive`](https://git-scm.com/docs/git-archive) which doesn't include submodules, as those are only pointers to other remote repositories ([see `.gitmodules`](https://git-scm.com/docs/gitmodules)).

This means you will have to clone the project with submodules using `git clone --recurse-submodules` in order to get the dependencies.

I agree that it would be nice if the project could use CMake to handle the dependencies and download them as you build, rather than git submodules.

**Comment by GabZach** [comment]
I see. But at least the zip on shadered.org should contain everything, IMHO.

**Comment by dfranx** [comment]
@xinaesthete I've just pushed a commit ( 5946dcf0a5ed42e733f6a81064658c82e8a8d57f ) that adds assimp as a submodule. That might fix your problem as now SHADERed won't search for precompiled assimp library but it is instead going to compile it.
