### ISSUE TITLE
backspace behaves like anti-tab in HLSL

### ISSUE THREAD

**Issue by eqbic** [dfranx/SHADERed#68]
I use the 1.3 Win64-portable Version.
if I start a new HLSL project and want to delete the last character I have written with 'backspace' it deletes the last character and the cursor jumps 3 positions to the left. 
this bug seems to appear only in HLSL code editor and not for GLSL

**Comment by Calinou** [comment]
I can reproduce this on Fedora 31, both on 1.3 and https://github.com/dfranx/SHADERed/commit/785783b7eb38c01c6b09558ba94bb6af6c6da7af.

**Comment by dfranx** [comment]
Thanks for reporting!
It happened on any line that used tabs. It's nice to know that I've shipped v1.3 with such major bug 😢 
But anyway, should be fixed now..
