### ISSUE TITLE
Compute shader are empty

### ISSUE THREAD

**Issue by hodasemi** [dfranx/SHADERed#69]
When I try to open a compute shader for editing inside SHADERed it appears always empty. This does apply for all example projects, as well as personal test project. I can write content to that file, but saving will overwrite the old content. When I reopen the project the same problem occurs. 

I'm running the Archlinux-AUR version at commit 52723288ef59e4d682bcc52a362d738cb776daca.

**Comment by dfranx** [comment]
Thanks for reporting! I've just pushed a fix for this bug. I guess the AUR package needs to get updated now - that's not in my control.

**Comment by hodasemi** [comment]
Works perfectly, thank you.
