### ISSUE TITLE
typing "a=;" then saving

### ISSUE THREAD

**Issue by unnamed54** [dfranx/SHADERed#73]
typing :

a=; 

in the text editor, then doing ctr+s crashes the application.

**Comment by dfranx** [comment]
I can't reproduce this bug.
Can you provide more details? By text editor, do you mean the built-in one? Also, what language?

**Comment by unnamed54** [comment]
When starting a new project and adding "a=;" at the beginning of the vertex shader (of the Simple shader) I can reproduce the bug:

#version 330

a=;

uniform mat4 matVP;
uniform mat4 matGeo;

layout (location = 0) in vec3 pos;
layout (location = 1) in vec3 normal;

out vec4 color;

void main() {
   color = vec4(abs(normal), 1.0);
   gl_Position = matVP * matGeo * vec4(pos, 1);
}

**Comment by dfranx** [comment]
Weird, I am not completely sure what's causing this. It might be a driver bug..?
For me, it just throws an error:
![driver](https://user-images.githubusercontent.com/30801537/76019262-b7c63080-5f21-11ea-8c8c-1e5029508939.png)
