### ISSUE TITLE
Downloaded App Does Not Launch on Linux (Ubuntu 18)

### ISSUE THREAD

**Issue by Rickodesea** [dfranx/SHADERed#74]
When the app is downloaded and unzipped, and attempted to be launch, error is received that assimp and sfml-audio-2.5 .so libraries are missing.  Assimp library  was installed separately successfully.  However unable to install sfml-2.5.  A call to "sudo apt-get install libsfml-dev" installed sfml-2.4 instead.  Suggestion: [Bundle required libraries with App download for linux users].

**Comment by Calinou** [comment]
> Suggestion: [Bundle required libraries with App download for linux users].

This now exists in the form of a [Flatpak](https://flathub.org/apps/details/org.shadered.SHADERed) :slightly_smiling_face: 

Before installing it, follow the setup guide here: https://flatpak.org/setup/Ubuntu/

**Comment by Rickodesea** [comment]
Thanks.  Your recommendation of Flatpak works.  I am now using the software and enjoying.  It is a good software you guys made,  well done.
