### ISSUE TITLE
Use clang-format to make code style more consistent

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#75]
We could start using [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to make the code style more consistent.

As for style, we can either create a custom style or use a predefined one. Personally, I've found the built-in WebKit style to look quite good, although it uses 4 spaces for indentation. Most of SHADERed's code uses tabs for indentation (with some files using 4 spaces). I tried customizing the WebKit style to use tabs instead, but it behaved weirdly with clang-format 6 (the resulting code had spaces and tabs mixed).

There are three main ways to use clang-format:

- Using an IDE tool or add-on.
  - This is a convenient option, but it needs to be coupled with the options below. Otherwise, there's no guarantee the code will remain style consistent over time.

- Using a Git pre-commit hook, so that all code will formatted properly before being committed.
  - Feel free to borrow [this folder from the Godot repository](https://github.com/godotengine/godot/tree/master/misc/hooks) :slightly_smiling_face: (note that you don't need `pre-commit-makerst` as it's Godot-specific).

- Using continuous integration (which we should set up in the future). This way, code style violations can be reported by the continuous integration service as a CI failure.

**Comment by dfranx** [comment]
I've added the `.clang-format` file ( 76109193f75a0f6195dce0c41ce85a66d97dd1c2 ). Could you please check if everything is okay before we apply it?
Though, there's one thing that's bothering me. I don't know how to make it to not put each element in array initializer in a new line.
For example:
```c++
GLfloat sth[] = {
   1.0f, 2.0f,
   3.0f, 4.0f
};
```
would become:
```c++
GLfloat sth[] = {
   1.0f,
   2.0f,
   3.0f,
   4.0f
};
```

This mostly affects `Engine/GeometryFactory.cpp` file and makes it ugly...

**Comment by Calinou** [comment]
> Though, there's one thing that's bothering me. I don't know how to make it to not put each element in array initializer in a new line.

You can add "ignore" comments to tell clang-format not to format a specific section:

```cpp
// clang-format off
GLfloat sth[] = {
   1.0f, 2.0f,
   3.0f, 4.0f
};
// clang-format on
```

**Comment by dfranx** [comment]
Thanks!
I reformatted every file. I've also added git hooks and added code style checks in CI.
I've also set up git hooks and made my IDE use the `.clang-format` file.

This is my first time doing any of this, so please feel free to modify anything.

I guess I can close this issue now since all proposed updates have been implemented.
