### ISSUE TITLE
Set up continous integration

### ISSUE THREAD

**Issue by Calinou** [dfranx/SHADERed#76]
We should set up continous integration so we can catch build errors and [code style violations](https://github.com/dfranx/SHADERed/issues/75) in commits and pull requests directly as they're pushed.

GitHub Actions seems to be an increasingly popular option since it's officially endorsed by GitHub, although it may not be the easiest option for a C++ project. If it doesn't pan out well, we could always fall back to Travis CI.

**Comment by dfranx** [comment]
I've set up CI (using GitHub Actions) for catching build errors (it currently runs on Ubuntu only) and for code style violations.
I wasn't sure if I should put building and code style checks in the same workflow so I put them in separate workflows.

**Comment by Calinou** [comment]
> I wasn't sure if I should put building and code style checks in the same workflow so I put them in separate workflows.

It makes sense to split them into separate workflows, especially after you start building for multiple platforms in parallel. This way, you can run code style checks before any platform is built.
