### ISSUE TITLE
3D Texture won't load

### ISSUE THREAD

**Issue by Jlkam** [dfranx/SHADERed#78]
3D Texture dds won't load.
(Windows Version)

**Comment by Calinou** [comment]
Can you upload the 3D texture DDS here for easier troubleshooting? You can add it to a ZIP archive and upload the ZIP here so GitHub accepts it.

**Comment by Jlkam** [comment]
I also tested 2D textures with the same result.
[shadered_dds_issue.zip](https://github.com/dfranx/SHADERed/files/4290186/shadered_dds_issue.zip)

Thanks you for your effort.
(Windows Version x64)

**Comment by dfranx** [comment]
Thank you for providing the textures.

SHADERed currently uses stb's stb_image to load textures. That library currently doesn't support DDS file format.
I guess I could either add a library which is able to load DDS files or replace stb_image. But I still haven't found any lightweight library that does that and I've decided against writing my own since I think it would be a major time loss.

**Comment by Jlkam** [comment]
Too bad :(

You can get basic DDS support by using e.g. freeimage (DXT1/3/5) but the main problem of the most library is the lag of extend format support e.g. uncompressed format or DX10+ BC1 to 7.

Maybe this can be a solution:
[DirectXTex](https://github.com/microsoft/DirectXTex)
[DDSTextureLoader.cpp](https://github.com/microsoft/DirectXTex/blob/master/DDSTextureLoader/DDSTextureLoader.cpp)
see LoadTextureDataFromMemory, LoadTextureDataFromFile

Keep up your good work!

**Comment by Calinou** [comment]
> This code is designed to build with Visual Studio 2017 (15.9), Visual Studio 2019, or clang for Windows v9. It is recommended that you make use of the Windows 10 May 2019 Update SDK (18362).

DirectXTex isn't cross-platform :slightly_frowning_face:

**Comment by jandy123** [comment]
I was wondering, are 3D texture supported for GLSL shaders ? 

Thanks !

**Comment by haraldreingruber-dedalus** [comment]
I am also interested in loading 3d textures, which file format does work for 3d?
I have my 3D tex data stored in a raw 16-bit grayscale format (medical data). I guess that would need to be converted first to be used...

On the other hand, a raw image loader might be easy to contribute, what do you think about this scenario?

**Comment by haraldreingruber-dedalus** [comment]
Ah, I think now I understand. Could it be that the current 3D Texture support is just for Image3D Objects, but not loading 3D textures from file?

**Comment by jandy123** [comment]
> Ah, I think now I understand. Could it be that the current 3D Texture support is just for Image3D Objects, but not loading 3D textures from file?

Yep.

**Comment by dfranx** [comment]
@haraldreingruber-dedalus Yeah, there's currently only Image3D objects (objects which can be written to with compute shaders and then used elsewhere). It's not possible to load 3D textures from files right now, but I am slowly working on my own DDS loader (it should be included in v1.5 release).
As for RAW, as far as I know, there are many types of RAW formats (which tell how and where the width, height, depth, content type are defined) so I am not sure if it would benefit SHADERed.

**Comment by haraldreingruber-dedalus** [comment]
@dfranx We use a simplified version (only basic required metadata) of the MHD format. The .mhd file has a few lines about the dimensions (x-, y-, z-size) and a .raw file containing the raw ushort (16bit) grayscale values.

If we try to extend it, maybe it would still be interesting as a plugin? I guess otherwise we would just try it out in our fork.

**Comment by dfranx** [comment]
Hey @Jlkam ! The ability to load 3D (and 2D) textures from .dds files has been implemented and will be working in SHADERed v1.5. Closing this issue!

@haraldreingruber-dedalus sorry for the slow response, slowly getting lost in these issues.. Maybe .mhd is too specific. I guess it could work as a plugin or you can implement it in your own fork. I might implement this if I get more requests or something though.
