### ISSUE TITLE
Insane GPU utilization on Manjaro - Nvidia GTX 1050

### ISSUE THREAD

**Issue by Nolkaloid** [dfranx/SHADERed#80]
I recently discovered SHADERed and I find it amazing, but I have issues using it on my Linux machine: 
**OS:** Manjaro
**GPU:** GTX 1050 2GB - linux-latest-nvidia-440xx drivers

Whenever SHADERed is open, even with the preview hidden, my GPU utilization goes nuts and fans start spinning like crazy once the temperature rises. See screenshot below:
![Screenshot_20200307_205727](https://user-images.githubusercontent.com/30960698/76151570-cc87fd00-60b6-11ea-96c1-7cd110cea03f.png)

Is this normal?

**Comment by dfranx** [comment]
Thank you for reporting!
Well yeah, high GPU usage is actually normal when FPS is not limited. SHADERed by default makes the GPU draw as fast as possible. This obviously causes the GPU utilization to be high.
To fix this, either turn on vertical sync (`Settings -> General -> VSync`) or limit the FPS (`Settings -> Preview -> FPS limit` & turn on the `Apply the FPS limit to the whole app`).
This will significantly lower the GPU usage percentage.

**Comment by Nolkaloid** [comment]
Oh thank you! Maybe enable this by default
