### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by anacierdem** [dfranx/SHADERed#82]
Window opens but app closes after some time.

**Comment by dfranx** [comment]
Hello!
Does this happen randomly or when you do a certain thing in SHADERed?
Could you please turn on the "Log" and "Stream logs to log.txt" options and then send me the log.txt file after a crash occurs?
Also, sorry for a late response.

**Comment by Calinou** [comment]
@anacierdem Bump :slightly_smiling_face: 

Which graphics card model do you have?

**Comment by anacierdem** [comment]
I have  gtx 560 ti. Ill try to provide more derails when I have the time.

**Comment by anacierdem** [comment]
This is not reproducible anymore. Maybe I have tried on a remote connection I don't remember. Is it possible to make this work on a remote desktop connection? We can safely close this one though.

**Comment by Calinou** [comment]
> Is it possible to make this work on a remote desktop connection?

Material Maker requires OpenGL acceleration to work. If remote desktop doesn't expose it, then it won't work. You may be able to deploy [mesa-dist-win](https://github.com/pal1000/mesa-dist-win) system-wide to make it work while using RDP.
