### ISSUE TITLE
no template named 'unordered_map'

### ISSUE THREAD

**Issue by GabZach** [dfranx/SHADERed#84]
On macOS Catalina, I get this compile error:

/Users/USER/Downloads/SHADERed/src/SHADERed/Objects/Debug/PixelInformation.h:45:8: error: 
      no template named 'unordered_map' in namespace 'std'
                std::unordered_map<std::string, bv_variable> VertexShade...

Solution:

#include <unordered_map>

in src/SHADERed/Objects/Debug/PixelInformation.h

**Comment by dfranx** [comment]
Thanks for reporting - should be fixed now!
