### ISSUE TITLE
Windows 10 crash

### ISSUE THREAD

**Issue by Ok23** [dfranx/SHADERed#85]
Crash instantly after i run exe
In log: Failed to initialize GLEW

**Comment by dfranx** [comment]
Hmm.. Not really sure what causes this.. What GPU do you have? What OpenGL version does it support?

**Comment by Ok23** [comment]
Intel hd 3000, ogl 3.1

**Comment by Calinou** [comment]
@Ok23 I'm afraid this IGP is too old to run most modern applications :slightly_frowning_face: 

Even on Linux which has better OpenGL support for old Intel IGPs, I wouldn't expect it to work well.

**Comment by Ok23** [comment]
Thanks, i will try

**Comment by Ok23** [comment]
But Aida64 and GPU-Z tells HD 3000 support OGL 3.1

**Comment by Calinou** [comment]
@Ok23 Sorry, I forgot it was actually OpenGL 3.1. I corrected my comment.

**Comment by Ok23** [comment]
SHADERed require OpenGL 3.3 ?
