### ISSUE TITLE
Question: How can I render to a screenQuad?

### ISSUE THREAD

**Issue by JoseMiguelPizarro** [dfranx/SHADERed#87]
Hi. I'm new to HLSL and I'm trying to render a ScreenQuad using a shader pass. But all I see is black. What is the proper way to render to a ScreenQuad? Thanks in advance

**Comment by dfranx** [comment]
ScreenQuad or ScreenQuadNDC?
You have to multiply ScreenQuad's position vertex attribute with the orthographic projection matrix & and geometry transform matrix. 
Also, there are plenty of examples that use ScreenQuad, you can check them too.
