### ISSUE TITLE
Ubuntu libassimp.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by johhnry** [dfranx/SHADERed#88]
Hi,

I just downloaded the latest version of SHADERed v1.3.2 for Linux and I am using Pop!_OS 19.10 (highly derived from Ubuntu).

When I run the executable, it says : 

```
@pop-os:~/Téléchargements/SHADERed$ ls
data              icon_32x32.png  libgtk-3.so.0           libsfml-system.so.2.5  themes
examples          icon_64x64.png  libSDL2-2.0.so.0        plugins
icon_128x128.png  libassimp.so.4  libsfml-audio.so.2.5    SHADERed
icon_256x256.png  libGLEW.so.2.1  libsfml-network.so.2.5  templates
@pop-os:~/Téléchargements/SHADERed$ ./SHADERed 
./SHADERed: error while loading shared libraries: libassimp.so.4: cannot open shared object file: No such file or directory

```

What am I doing wrong?

**Comment by dfranx** [comment]
Thanks for pointing this out.
Can you check if the v1.3.1 works for you?

**Comment by johhnry** [comment]
No it doesn't work either : 

```shell
@pop-os:~/Téléchargements/SHADERed$ ls
Linux.zip

@pop-os:~/Téléchargements/SHADERed$ unzip Linux.zip 
Archive:  Linux.zip
   creating: SHADERed/
...
...

@pop-os:~/Téléchargements/SHADERed$ ls
Linux.zip  SHADERed

@pop-os:~/Téléchargements/SHADERed$ ./SHADERed/SHADERed 
./SHADERed/SHADERed: error while loading shared libraries: libassimp.so.4: cannot open shared object file: No such file or directory
josephhenry@pop-os:~/Téléchargements/SHADERed$ 
```

**Comment by tynrare** [comment]
@johhnry just `ln -s /lib/libassimp.so /lib/libassimp.so.4`

@Calinou it's already libassimp.so.5 on linux systems

**Comment by Calinou** [comment]
@tynrare Are those Assimp versions compatible with each other?

**Comment by johhnry** [comment]
Hi @tynrare, thanks for your answer but it doesn't work : 

```shell
@pop-os:~/Téléchargements/SHADERed_v1.3.2$ ls
data      icon_128x128.png  icon_32x32.png  libassimp.so.4  libgtk-3.so.0     libsfml-audio.so.2.5    libsfml-system.so.2.5  SHADERed   themes
examples  icon_256x256.png  icon_64x64.png  libGLEW.so.2.1  libSDL2-2.0.so.0  libsfml-network.so.2.5  plugins                templates

@pop-os:~/Téléchargements/SHADERed_v1.3.2$ sudo ln -s /lib/libassimp.so /lib/libassimp.so.4

@pop-os:~/Téléchargements/SHADERed_v1.3.2$ ./SHADERed 
./SHADERed: error while loading shared libraries: libassimp.so.4: cannot open shared object file: No such file or directory
```

**Comment by tynrare** [comment]
@Calinou this works for me (Application itself works fine), but i experience lot of bugs like sometimes texture uniform uv randomly binds to mouse position (Relaunch helps). Don't sure it global bug or it somehow related with assimp.

@johhnry do you have /lib/libassimp.so? And is there /lib/libassimp.so.4 after you linked it? Try to link /lib/libassimp.so.5 instead, maybe it will help. Also you can try `sudo ln -s ~/Téléchargements/SHADERed/libassimp.so.4 /lib/libassimp.so.4`. Honestly i don't sure how all this shared objects stuff works in linux, but in general you need put (libassimp.so.4) file somewhere system can find it. Also try to launch files in places that doesn't contain non-standard symbols in path like yours *Téléchargements*

**Comment by dfranx** [comment]
@tynrare that's weird. I've never experienced such bugs. If you find a way to reproduce it please open an issue. I'd be willing to fix it in the next release.

@johhnry As suggested by @Calinou , I think installing SHADERed using the Flatpak might be an easier solution.

**Comment by johhnry** [comment]
@tynrare 
It's strange because I have `libassimp-dev` (4.1.0~dfsg-5) installed but there's no `.so` file in `/lib`.
But anyway, this command worked : 
`sudo ln -s ~/Téléchargements/SHADERed/libassimp.so.4 /lib/libassimp.so.4`

Thanks for the help!

@dfranx 
Thanks, I finally compiled SHADERed myself :+1:
