### ISSUE TITLE
Debug Fetch Crashes App if Two Textures Are Sampled in PS

### ISSUE THREAD

**Issue by BVS3** [dfranx/SHADERed#92]
I'm attempting to sample two textures in a pixel shader.  I have them both added as objects and bound to (0) and (1) and am referencing them in code as follows:
Texture2D tex : register(t0);
Texture2D tex2 : register(t1);
SamplerState smp : register(s0);
SamplerState smp2 : register(s2);

When that tex2 and smp2 are in the code, Debug->fetch will crash the program.   This happens regardless of the texture used or if I do anything with tex2/smp2 later on in the code or not.  

I turned on the log option and attached the file, however I didn't see any errors in the output. 

[log.txt](https://github.com/dfranx/SHADERed/files/4438354/log.txt)

**Comment by dfranx** [comment]
Thanks for reporting. The fix for this will be included in v1.3.4 (in ~4 weeks) since I've just released [SPIRV-VM](https://github.com/dfranx/SPIRV-VM) and it will take me some time to port everything from ShaderDebugger to SPIRV-VM. And I'd rather not waste time fixing the ShaderDebugger right now, if that's not a problem.

**Comment by Trass3r** [comment]
For me Fetch doesn't crash but reports a cryptic error: `memory:83:9: error: syntax error during unary prefix`. But I guess this will also be fixed by the switch as it seems to come from https://github.com/graphitemaster/glsl-parser/blob/9301700b6a5fc89031b9de951eead46e08916a95/parser.cpp#L968

**Comment by dfranx** [comment]
@Trass3r @BVS3 I've just released an update that possibly fixes this. I've switched from ShaderDebugger to SPIRV-VM so the debugger should overall be more stable now. Could you please try that code again, if possible, and report back here if everything works?

**Comment by BVS3** [comment]
@dfranx  - Crash looks to be fixed after the latest release.  Thanks so much!
