### ISSUE TITLE
Is there any way to bind big buffer objects?

### ISSUE THREAD

**Issue by Inori** [dfranx/SHADERed#93]
I mean, like textures, to load the buffer data from a file.
becuase typically, storage buffers are pretty big.
what's the best way to bind a storage buffer?

sorry to disturb.

**Comment by dfranx** [comment]
Hey!

Not sure if I understood correctly but what you wqnt is to be able to load texture (or other file types) data into a SHADERed's buffer object?
If so, I could try to implement this for tomorrows v1.3.3 release 😊

Thank you so much for this idea!

**Comment by Inori** [comment]
Thanks for your replay.

It's just simple binary data, used for SSBOs or UBOs.
Some of the buffer object is too large to edit every item manually, so I think it's better
to have some ways to load from file, just like the textures.
How to interpret the data structure depends on the shader code,
this way we keep it generic.

e.g.
```
layout(binding = 0) buffer SSBO0
{
	uint g_cell[];
};

layout(binding = 1) buffer SSBO1
{
	uint g_font[];
};

layout(binding = 2) uniform UBO0
{
	uvec4 g_color[16][4];
};
```

btw: the above buffer declaration will trigger an error when I try to debug the shader and press the `fetch` button.
![QQ截图20200417023910](https://user-images.githubusercontent.com/6732524/79494126-10c2d180-8055-11ea-965d-308d201ccb4b.jpg)

**Comment by dfranx** [comment]
Added with the commit f3f52f8f9f14d8a0b2c3497cf7cdbd95170f835f .
Feedback is welcome!
