### ISSUE TITLE
Tutorial: no 2d version

### ISSUE THREAD

**Issue by Zireael07** [dfranx/SHADERed#94]
All I want is to test a simple spritesheet shader. However, I can't figure out how to apply a shader, or how to place two quads in the scene (so that I can test layering)

**Comment by dfranx** [comment]
I can create a simple 2D project. What language do you want it in?

**Comment by Zireael07** [comment]
GLSL, please.

**Comment by dfranx** [comment]
[2Dexample.zip](https://github.com/dfranx/SHADERed/files/4524592/2Dexample.zip)

You should see 2 quads on the screen. If you need help with anything, have a suggestion/feature request or you've got questions feel free to ask.

**Comment by Zireael07** [comment]
Thanks for the example.

For beginner users, who only know a bit of GLSL and/or want to drop in immediately, it would be useful if ShadeRED had project templates: for 3d, a cube and a, let's say all red shader, and similarly for 2d, a single quad and a single color shader. 
Users shouldn't be required to first create files manually before doing anything with shaders - ref https://github.com/dfranx/SHADERed/blob/master/TUTORIAL.md

**Comment by dfranx** [comment]
Sure, thanks for the suggestion. I'll definitely expand the templates. I'll also try to improve the UX by not requesting users to create files manually.

**Comment by dfranx** [comment]
> Users shouldn't be required to first create files manually before doing anything with shaders

@Zireael07 Thank you so much for this suggestion. I think it improves the UX so much.

I've added this in v1.3.4, if this is what you've meant:
![AutoShaders](https://user-images.githubusercontent.com/30801537/82155952-aaf67f00-9878-11ea-860a-ca873ad05eae.gif)

**Comment by Zireael07** [comment]
Yes, that's what I meant, thank you very much for this!
