### ISSUE TITLE
Screen space quad doesn't render

### ISSUE THREAD

**Issue by dubik** [dfranx/SHADERed#97]
When I open Shadered, I remove cube and add ScreenQuad.
I change pixel shader to output red:
```glsl
#version 330

in vec4 color;
out vec4 outColor;

void main() {
   outColor = vec4(1.0f, 0.0f, 0, 1.0f);
}
```

but preview is black. If I add any other geometry, it renders fine(red). I checked that ScreenQuad position is 0,0,0 and scale is 1.0, 1.0, 1.0. What am I missing? I found 2dexample.zip  and screenquad works fine there. 
Thanks!

**Comment by dfranx** [comment]
You have to use orthographic matrix instead of projection matrix when using ScreenQuad.
