### ISSUE TITLE
How do I reset the view?

### ISSUE THREAD

**Issue by Gavin-Williams** [dfranx/SHADERed#98]
Hi,

How do I reset the view? I've lost the object.

**Comment by dfranx** [comment]
Hey!
What do you mean you lost your object?
Not sure what exactly this means, but:

1. If you moved your object out of the camera's view you can right click on the object in the pipeline manager -> properties and then change it's position from the property window. 
2. If you zoomed in on a pixel region (ALT + selecting a region) you can either ALT + double click on a preview window and the zoom will reset. Or you can use the +/- buttons in the preview window's status bar. If you need to move the "zoom region" just hold alt and drag with right mouse button. 


Also, with the default camera you can move forward/backwards with the mouse wheel. But you can also activate the first person view camera in the Options -> Project which then allows you to take more control of the camera's properties (position and orientation)
